Repository jorgecarleitao/arrow2, pull requests merged in 2021-10, with the labels that each got.

#485 Implement `BitXor` trait for `Bitmap`
  src/bitmap/bitmap_ops.rs
Labels: feature

#467 expose `shrink_to_fit` to mutable arrays
  src/array/binary/mutable.rs
  src/array/boolean/mutable.rs
  src/array/dictionary/mutable.rs
  src/array/fixed_size_binary/mutable.rs
  src/array/fixed_size_list/mutable.rs
  src/array/list/mutable.rs
  src/array/mod.rs
  src/array/primitive/mutable.rs
  src/array/utf8/mutable.rs
Labels: feature

#483 Improved inference and deserialization of CSV
  Cargo.toml
  src/io/csv/read/deserialize.rs
  src/io/csv/read/infer_schema.rs
  src/io/csv/read/mod.rs
  src/io/csv/read/reader.rs
  tests/it/io/csv/read.rs
Labels: enhancement

#464 Added support for `DataType::Map` and `MapArray`
  README.md
  arrow-pyarrow-integration-testing/tests/test_sql.py
  integration-testing/unskip.patch
  src/array/display.rs
  src/array/equal/map.rs
  src/array/equal/mod.rs
  src/array/ffi.rs
  src/array/growable/mod.rs
  src/array/list/mod.rs
  src/array/map/ffi.rs
  src/array/map/iterator.rs
  src/array/map/mod.rs
  src/array/mod.rs
  src/compute/aggregate/memory.rs
  src/datatypes/field.rs
  src/datatypes/mod.rs
  src/datatypes/physical_type.rs
  src/ffi/array.rs
  src/ffi/ffi.rs
  src/ffi/schema.rs
  src/io/ipc/convert.rs
  src/io/ipc/read/array/map.rs
  src/io/ipc/read/array/mod.rs
  src/io/ipc/read/deserialize.rs
  src/io/ipc/write/serialize.rs
  src/io/json_integration/read.rs
  src/io/json_integration/schema.rs
  src/io/parquet/read/primitive/dictionary.rs
  src/scalar/mod.rs
  tests/it/io/ipc/read/file.rs
  tests/it/io/ipc/write/file.rs
Labels: feature

#487 Made `hash` work for extension type
  src/compute/hash.rs
Labels: enhancement

#489 Added read `Decimal` from parquet
  parquet_integration/write_parquet.py
  src/io/parquet/read/mod.rs
  src/io/parquet/read/schema/convert.rs
  src/io/parquet/read/schema/metadata.rs
  src/io/parquet/read/statistics/fixlen.rs
  src/io/parquet/read/statistics/mod.rs
  src/io/parquet/read/statistics/primitive.rs
  src/io/parquet/write/fixed_len_bytes.rs
  tests/it/io/parquet/mod.rs
  tests/it/io/parquet/read.rs
  tests/it/io/parquet/write.rs
Labels: feature

#495 Updated patch for integration.
  integration-testing/unskip.patch
Labels: testing

#510 Do not check offsets or utf8 validity in ffi (#505)
  src/array/binary/ffi.rs
  src/array/binary/mod.rs
  src/array/utf8/ffi.rs
Labels: bug

#518 Change IPC `FileReader` to own the underlying reader
  examples/extension.rs
  examples/ipc_file_read.rs
  integration-testing/src/bin/arrow-file-to-stream.rs
  integration-testing/src/bin/arrow-json-integration-test.rs
  src/io/ipc/read/reader.rs
  tests/it/io/ipc/read/file.rs
  tests/it/io/ipc/write/file.rs
Labels: backwards-incompatible

#523 Fixed error in writing compressed parquet dict pages
  src/io/parquet/write/dictionary.rs
  tests/it/io/parquet/write.rs
Labels: bug

#531 Fixed unskip patch.
  integration-testing/unskip.patch
Labels: testing, no-changelog

#533 Improved parquet read benches
  benches/read_parquet.rs
  benchmarks/.gitignore
  benchmarks/bench_read.py
  benchmarks/run.py
  benchmarks/summarize.py
  parquet_integration/bench_read.py
  parquet_integration/write_parquet.py
Labels: testing

#532 Simplified reading parquet
  Cargo.toml
  examples/parquet_read.rs
  examples/parquet_read_parallel.rs
  examples/parquet_write.rs
  src/io/parquet/mod.rs
  src/io/parquet/read/binary/basic.rs
  src/io/parquet/read/binary/dictionary.rs
  src/io/parquet/read/binary/nested.rs
  src/io/parquet/read/boolean/basic.rs
  src/io/parquet/read/boolean/nested.rs
  src/io/parquet/read/fixed_size_binary.rs
  src/io/parquet/read/mod.rs
  src/io/parquet/read/primitive/dictionary.rs
  src/io/parquet/read/primitive/mod.rs
  src/io/parquet/write/binary/basic.rs
  src/io/parquet/write/binary/nested.rs
  src/io/parquet/write/boolean/basic.rs
  src/io/parquet/write/boolean/nested.rs
  src/io/parquet/write/dictionary.rs
  src/io/parquet/write/fixed_len_bytes.rs
  src/io/parquet/write/mod.rs
  src/io/parquet/write/primitive/basic.rs
  src/io/parquet/write/primitive/nested.rs
  src/io/parquet/write/record_batch.rs
  src/io/parquet/write/utf8/basic.rs
  src/io/parquet/write/utf8/nested.rs
  src/io/parquet/write/utils.rs
  tests/it/io/parquet/mod.rs
Labels: backwards-incompatible

#537 Ignored RUSTSEC-2020-0071 and RUSTSEC-2020-0159
  .cargo/audit.toml
Labels: testing

#556 Change DataType::FixedSize*(i32) to DataType::FixedSize*(usize)
  src/array/fixed_size_binary/mod.rs
  src/array/fixed_size_binary/mutable.rs
  src/array/fixed_size_list/mod.rs
  src/array/growable/fixed_binary.rs
  src/datatypes/mod.rs
  src/io/avro/read/schema.rs
  src/io/ipc/convert.rs
  src/io/ipc/read/array/fixed_size_binary.rs
  src/io/json_integration/schema.rs
  src/io/parquet/read/fixed_size_binary.rs
  src/io/parquet/read/mod.rs
  src/io/parquet/read/schema/convert.rs
  src/io/parquet/read/statistics/fixlen.rs
  src/io/parquet/write/mod.rs
  src/io/parquet/write/schema.rs
Labels: backwards-incompatible

#557 Introduced `UnionMode` enum
  src/array/union/mod.rs
  src/datatypes/mod.rs
  src/ffi/schema.rs
  src/io/avro/read/schema.rs
  src/io/ipc/convert.rs
  src/io/ipc/read/array/union.rs
  src/io/json_integration/schema.rs
  tests/it/array/mod.rs
  tests/it/array/union.rs
  tests/it/io/print.rs
Labels: backwards-incompatible

#559 Avoid unnecessary allocations
  src/array/display.rs
  src/ffi/schema.rs
Labels: enhancement

#558 Surfaced errors in reading from avro
  Cargo.toml
  benches/avro_read.rs
  src/io/avro/read/mod.rs
Labels: enhancement

#553 Added bitwise operations
  Cargo.toml
  benches/bitwise.rs
  src/compute/bitwise.rs
  src/compute/mod.rs
  tests/it/compute/bitwise.rs
  tests/it/compute/mod.rs
Labels: feature

#560 Avoided redundant checks in creating an `Utf8Array` from `MutableUtf8Array`
  src/array/utf8/mutable.rs
Labels: enhancement
