Repository jorgecarleitao/arrow2, pull requests merged in 2021-08, with the labels that each got.

#239 Added support to parquet IO on wasm32
  .github/workflows/test.yml
  Cargo.toml
Labels: enhancement

#250 Fixed error in slicing bitmap.
  src/bitmap/immutable.rs
  src/bitmap/utils/slice_iterator.rs
Labels: bug

#247 Added IndexRange to remove checks in hot loops
  src/array/mod.rs
  src/array/specification.rs
  src/buffer/mutable.rs
  src/compute/sort/boolean.rs
  src/compute/sort/common.rs
  src/compute/sort/lex_sort.rs
  src/compute/sort/mod.rs
  src/compute/sort/primitive/indices.rs
  src/compute/sort/utf8.rs
  src/compute/take/mod.rs
  src/types/index.rs
  src/types/mod.rs
Labels: backwards-incompatible, enhancement

#253 Added more tests to cast and min/max
  src/compute/aggregate/min_max.rs
  src/compute/cast/mod.rs
Labels: enhancement

#254 Added wrapping_cast to cast kernels
  src/compute/cast/dictionary_to.rs
  src/compute/cast/mod.rs
  src/compute/cast/primitive_to.rs
Labels: feature

#262 Fixed error in computing remainder of chunk iterator
  src/bitmap/utils/chunk_iterator/mod.rs
  src/bitmap/utils/mod.rs
Labels: bug

#265 Migrated to parquet2 v0.3
  Cargo.toml
  arrow-parquet-integration-testing/src/main.rs
  benches/write_parquet.rs
  examples/parquet_write.rs
  examples/parquet_write_record.rs
  src/io/parquet/mod.rs
  src/io/parquet/read/binary/basic.rs
  src/io/parquet/read/binary/nested.rs
  src/io/parquet/read/boolean/basic.rs
  src/io/parquet/read/boolean/nested.rs
  src/io/parquet/read/fixed_size_binary.rs
  src/io/parquet/read/mod.rs
  src/io/parquet/read/primitive/basic.rs
  src/io/parquet/read/primitive/dictionary.rs
  src/io/parquet/read/primitive/nested.rs
  src/io/parquet/read/schema/convert.rs
  src/io/parquet/read/utils.rs
  src/io/parquet/write/binary/nested.rs
  src/io/parquet/write/boolean/basic.rs
  src/io/parquet/write/boolean/nested.rs
  src/io/parquet/write/dictionary.rs
  src/io/parquet/write/fixed_len_bytes.rs
  src/io/parquet/write/mod.rs
  src/io/parquet/write/primitive/basic.rs
  src/io/parquet/write/primitive/nested.rs
  src/io/parquet/write/schema.rs
  src/io/parquet/write/stream.rs
  src/io/parquet/write/utf8/nested.rs
  src/io/parquet/write/utils.rs
Labels: enhancement, backwards-incompatible

#56 Scalar
  src/compute/aggregate/min_max.rs
  src/compute/aggregate/sum.rs
  src/lib.rs
  src/scalar/README.md
  src/scalar/binary.rs
  src/scalar/boolean.rs
  src/scalar/equal.rs
  src/scalar/list.rs
  src/scalar/mod.rs
  src/scalar/null.rs
  src/scalar/primitive.rs
  src/scalar/struct_.rs
  src/scalar/utf8.rs
Labels: enhancement, backwards-incompatible

#256 Added support to filter parquet pages.
  benches/read_parquet.rs
  examples/parquet_read.rs
  examples/parquet_read_parallel.rs
  examples/parquet_read_record.rs
  src/io/parquet/mod.rs
  src/io/parquet/read/mod.rs
  src/io/parquet/read/record_batch.rs
Labels: backwards-incompatible, feature

#260 Added support to read parquet asynchronously
  examples/s3/Cargo.toml
  examples/s3/src/main.rs
  examples/s3/src/stream.rs
  src/io/parquet/read/binary/basic.rs
  src/io/parquet/read/binary/mod.rs
  src/io/parquet/read/boolean/basic.rs
  src/io/parquet/read/boolean/mod.rs
  src/io/parquet/read/fixed_size_binary.rs
  src/io/parquet/read/mod.rs
  src/io/parquet/read/primitive/mod.rs
  src/io/parquet/write/utf8/nested.rs
Labels: backwards-incompatible, feature

#267 Added support for FFI of dictionary-encoded arrays
  arrow-pyarrow-integration-testing/tests/test_sql.py
  src/array/binary/ffi.rs
  src/array/boolean/ffi.rs
  src/array/dictionary/ffi.rs
  src/array/dictionary/mod.rs
  src/array/ffi.rs
  src/array/list/ffi.rs
  src/array/mod.rs
  src/array/primitive/ffi.rs
  src/array/struct_.rs
  src/ffi/array.rs
  src/ffi/ffi.rs
  src/ffi/mod.rs
  src/ffi/schema.rs
Labels: feature

#264 Added support for projection pushdown on IPC files
  arrow-flight/src/utils.rs
  examples/ipc_file_read.rs
  integration-testing/src/bin/arrow-file-to-stream.rs
  integration-testing/src/bin/arrow-json-integration-test.rs
  integration-testing/src/flight_server_scenarios/integration_test.rs
  src/io/ipc/read/array/binary.rs
  src/io/ipc/read/array/boolean.rs
  src/io/ipc/read/array/dictionary.rs
  src/io/ipc/read/array/fixed_size_binary.rs
  src/io/ipc/read/array/fixed_size_list.rs
  src/io/ipc/read/array/list.rs
  src/io/ipc/read/array/mod.rs
  src/io/ipc/read/array/null.rs
  src/io/ipc/read/array/primitive.rs
  src/io/ipc/read/array/struct_.rs
  src/io/ipc/read/array/utf8.rs
  src/io/ipc/read/common.rs
  src/io/ipc/read/deserialize.rs
  src/io/ipc/read/mod.rs
  src/io/ipc/read/read_basic.rs
  src/io/ipc/read/reader.rs
  src/io/ipc/read/stream.rs
  src/io/ipc/write/writer.rs
Labels: backwards-incompatible, feature

#276 Reduce dependencies from confi-table and enable wasm on io_print feature.
  .github/workflows/test.yml
  Cargo.toml
Labels: enhancement

#277 Simplified IPC code.
  src/io/ipc/read/read_basic.rs
Labels: enhancement

#280 Cleaned up internals of json integration
  src/io/json_integration/schema.rs
Labels: enhancement

#284 Improved debug repr of buffers and bitmaps.
  src/bitmap/immutable.rs
  src/bitmap/mutable.rs
  src/bitmap/utils/fmt.rs
  src/bitmap/utils/mod.rs
  src/buffer/immutable.rs
  src/buffer/mutable.rs
Labels: enhancement

#285 Removed order implementation for `days_ms` / `Interval(DayTime)`
  src/array/ord.rs
  src/compute/comparison/mod.rs
  src/compute/sort/mod.rs
  src/types/mod.rs
Labels: bug

#287 Added support for timestamps with tz and interval to `io::print::write`
  examples/ipc_file_read.rs
  src/array/display.rs
  src/array/primitive/display.rs
  src/io/print.rs
Labels: enhancement

#290 Made CSV and JSON tests not use files.
  .github/workflows/test.yml
  src/io/json/read/infer_schema.rs
  src/io/json/read/reader.rs
  test/data/arrays.json
  test/data/basic.json
  test/data/basic_nulls.json
  test/data/integration.json
  test/data/list_string_dict_nested_nulls.json
  test/data/mixed_arrays.json
  test/data/mixed_arrays.json.gz
  test/data/nested_structs.json
  test/data/null_test.csv
  test/data/uk_cities.csv
  test/data/uk_cities_with_headers.csv
  test/data/various_types.csv
  test/data/various_types_invalid.csv
  tests/it/io/csv/read.rs
  tests/it/io/json/mod.rs
  tests/it/io/json/read.rs
Labels: enhancement

#291 Improved performance of concatenating non-aligned validities (15x)
  Cargo.toml
  benches/bitmap.rs
  benches/concat.rs
  src/array/growable/boolean.rs
  src/array/growable/utils.rs
  src/bitmap/mutable.rs
  src/bitmap/utils/chunk_iterator/mod.rs
  src/bitmap/utils/mod.rs
  tests/it/bitmap/mutable.rs
Labels: enhancement

#295 Fixed small inconsistencies between `compute::cast` and `compute::can_cast`
  src/compute/cast/mod.rs
  tests/it/compute/cast.rs
  tests/it/compute/mod.rs
  tests/it/main.rs
Labels: bug

#296 Generalized ZipIterator to accept a `BitmapIter`
  src/array/binary/iterator.rs
  src/array/boolean/iterator.rs
  src/array/dictionary/iterator.rs
  src/array/fixed_size_binary/iterator.rs
  src/array/fixed_size_list/iterator.rs
  src/array/list/iterator.rs
  src/array/primitive/iterator.rs
  src/array/utf8/iterator.rs
  src/bitmap/utils/zip_validity.rs
  tests/it/bitmap/utils/zip_validity.rs
Labels: backwards-incompatible

#297 Improved `MutableBooleanArray`
  src/array/boolean/iterator.rs
  src/array/boolean/mod.rs
  src/array/boolean/mutable.rs
  src/bitmap/mutable.rs
  tests/it/array/boolean/mutable.rs
Labels: enhancement

#299 Improved `MutablePrimitiveArray` and `MutableUtf8Array`
  src/array/boolean/mutable.rs
  src/array/mod.rs
  src/array/primitive/iterator.rs
  src/array/primitive/mutable.rs
  src/array/specification.rs
  src/array/utf8/from.rs
  src/array/utf8/mutable.rs
  tests/it/array/boolean/mutable.rs
  tests/it/array/mod.rs
  tests/it/array/primitive/mutable.rs
  tests/it/array/union.rs
  tests/it/array/utf8/mod.rs
Labels: enhancement

#300 Added tests to scalar API
  README.md
  src/scalar/binary.rs
  src/scalar/boolean.rs
  src/scalar/primitive.rs
  src/scalar/utf8.rs
  tests/it/array/boolean/mutable.rs
  tests/it/array/growable/struct_.rs
  tests/it/main.rs
  tests/it/scalar/binary.rs
  tests/it/scalar/boolean.rs
  tests/it/scalar/list.rs
  tests/it/scalar/mod.rs
  tests/it/scalar/null.rs
  tests/it/scalar/primitive.rs
  tests/it/scalar/struct_.rs
  tests/it/scalar/utf8.rs
Labels: testing

#304 Added support to read json to `BinaryArray`
  src/io/json/read/deserialize.rs
  tests/it/io/json/mod.rs
Labels: enhancement

#303 Improved MutableFixedSizeBinaryArray
  src/array/fixed_size_binary/iterator.rs
  src/array/fixed_size_binary/mod.rs
  src/array/fixed_size_binary/mutable.rs
  src/array/primitive/mutable.rs
  tests/it/array/fixed_size_binary/mutable.rs
Labels: enhancement

#305 Improved performance of comparison with SIMD feature flag (2x-3.5x)
  benches/comparison_kernels.rs
  src/compute/comparison/mod.rs
  src/compute/comparison/primitive.rs
  src/compute/comparison/simd/mod.rs
  src/compute/comparison/simd/native.rs
  src/compute/comparison/simd/packed.rs
  src/compute/nullif.rs
  src/trusted_len.rs
Labels: enhancement

#308 add cast `date32 -> i64` and `date64 -> i32`
  src/compute/cast/mod.rs
  tests/it/compute/cast.rs
Labels: enhancement

#313 Fixed error in SIMD comparisons
  .github/workflows/test.yml
  src/compute/comparison/simd/packed.rs
Labels: testing

#306 Improved documentation
  src/array/binary/iterator.rs
  src/array/binary/mod.rs
  src/array/boolean/from.rs
  src/array/boolean/iterator.rs
  src/array/boolean/mod.rs
  src/array/boolean/mutable.rs
  src/array/growable/mod.rs
  src/array/mod.rs
  src/array/primitive/mod.rs
  src/array/primitive/mutable.rs
  src/array/utf8/mod.rs
  src/bitmap/immutable.rs
  src/buffer/mutable.rs
  src/compute/concat.rs
  src/compute/merge_sort/mod.rs
  src/compute/nullif.rs
  src/io/json/read/infer_schema.rs
  src/types/mod.rs
Labels: documentation

#307 Removed clone requirement in `StructArray -> RecordBatch`
  src/array/struct_.rs
  src/record_batch.rs
  tests/it/record_batch.rs
Labels: enhancement, backwards-incompatible

#314 Added trait `TryPush`
  src/array/binary/mutable.rs
  src/array/boolean/mutable.rs
  src/array/list/mutable.rs
  src/array/mod.rs
  src/array/primitive/mutable.rs
  src/array/utf8/mutable.rs
  tests/it/array/list/mutable.rs
Labels: enhancement

#317 Added `compare_scalar`
  benches/comparison_kernels.rs
  src/compute/comparison/boolean.rs
  src/compute/comparison/mod.rs
  src/compute/comparison/primitive.rs
  src/compute/comparison/utf8.rs
Labels: feature

#315 Improved naming of testing workflows
  .github/workflows/integration-ffi.yml
  .github/workflows/integration-ipc.yml
  .github/workflows/integration-parquet.yml
Labels: testing

#318 Improved performance of boolean comparison (5x-14x)
  benches/comparison_kernels.rs
  src/compute/comparison/boolean.rs
Labels: enhancement

#302 Fixed error in reading a non-finished IPC stream.
  examples/ipc_pyarrow/.gitignore
  examples/ipc_pyarrow/Cargo.toml
  examples/ipc_pyarrow/main.py
  examples/ipc_pyarrow/run.sh
  examples/ipc_pyarrow/src/main.rs
  guide/src/SUMMARY.md
  guide/src/io/ipc_stream_read.md
  integration-testing/src/bin/arrow-file-to-stream.rs
  integration-testing/src/bin/arrow-stream-to-file.rs
  integration-testing/src/flight_client_scenarios/integration_test.rs
  integration-testing/src/flight_server_scenarios/integration_test.rs
  src/io/ipc/read/mod.rs
  src/io/ipc/read/stream.rs
  tests/it/io/ipc/common.rs
  tests/it/io/ipc/read/stream.rs
  tests/it/io/ipc/write/stream.rs
Labels: backwards-incompatible

#324 Made `multiversion` and `lexical-core` optional
  Cargo.toml
  src/util/lexical.rs
  src/util/mod.rs
Labels: enhancement

#322 Improved performance of utf8 comparison (1.7x-4x)
  benches/comparison_kernels.rs
  benches/filter_kernels.rs
  benches/sort_kernel.rs
  benches/take_kernels.rs
  benches/write_ipc.rs
  benches/write_parquet.rs
  src/compute/comparison/utf8.rs
  src/util/bench_util.rs
Labels: enhancement

#330 Cleaned examples and docs from old API.
  arrow-pyarrow-integration-testing/src/lib.rs
  benches/take_kernels.rs
  guide/src/ffi.md
  guide/src/high_level.md
  src/array/ord.rs
  src/compute/arithmetics/basic/add.rs
  src/compute/arithmetics/decimal/add.rs
  src/compute/arithmetics/decimal/div.rs
  src/compute/arithmetics/decimal/mul.rs
  src/compute/arithmetics/decimal/sub.rs
  src/compute/arithmetics/mod.rs
  src/compute/arithmetics/time.rs
  src/compute/filter.rs
  src/compute/take/list.rs
  src/io/json/write/serialize.rs
  src/record_batch.rs
  tests/it/io/json/write.rs
  tests/it/io/parquet/mod.rs
Labels: documentation

#321 Added API to FFI `Field`
  .github/workflows/integration-ffi.yml
  arrow-pyarrow-integration-testing/Cargo.toml
  arrow-pyarrow-integration-testing/src/lib.rs
  arrow-pyarrow-integration-testing/tests/test_sql.py
  examples/ffi.rs
  guide/src/ffi.md
  src/array/binary/ffi.rs
  src/array/boolean/ffi.rs
  src/array/list/ffi.rs
  src/array/primitive/ffi.rs
  src/array/struct_.rs
  src/array/union/ffi.rs
  src/ffi/array.rs
  src/ffi/ffi.rs
  src/ffi/mod.rs
  src/ffi/schema.rs
  tests/it/ffi.rs
Labels: feature

#334 Fixed error in displaying dictionaries with nulls in values
  src/array/display.rs
  tests/it/io/print.rs
Labels: bug

#333 Fixed error in dict equality
  src/array/dictionary/iterator.rs
  src/array/dictionary/mod.rs
  src/array/equal/dictionary.rs
  tests/it/array/equal/dictionary.rs
Labels: bug

#336 Added support for remaining non-nested datatypes
  arrow-parquet-integration-testing/main_spark.py
  src/io/parquet/read/binary/dictionary.rs
  src/io/parquet/read/binary/mod.rs
  src/io/parquet/read/mod.rs
  src/io/parquet/write/dictionary.rs
  src/io/parquet/write/mod.rs
  src/io/parquet/write/record_batch.rs
  tests/it/io/parquet/mod.rs
Labels: enhancement

#337 Added support for reading binary from CSV
  src/io/csv/read/deserialize.rs
  tests/it/io/csv/read.rs
Labels: feature

#353 Reduced dependencies within `num`
  Cargo.toml
  benches/arithmetic_kernels.rs
  src/array/dictionary/mod.rs
  src/array/specification.rs
  src/compute/arithmetics/basic/add.rs
  src/compute/arithmetics/basic/div.rs
  src/compute/arithmetics/basic/mul.rs
  src/compute/arithmetics/basic/pow.rs
  src/compute/arithmetics/basic/rem.rs
  src/compute/arithmetics/basic/sub.rs
  src/compute/arithmetics/mod.rs
  src/compute/arithmetics/time.rs
  src/compute/arity.rs
  src/compute/cast/boolean_to.rs
  src/compute/cast/dictionary_to.rs
  src/compute/cast/primitive_to.rs
  src/compute/window.rs
  src/io/json/read/deserialize.rs
  src/io/json_integration/read.rs
  src/io/parquet/read/statistics/primitive.rs
  src/io/parquet/write/primitive/basic.rs
  src/io/parquet/write/primitive/nested.rs
  src/types/index.rs
  tests/it/compute/cast.rs
Labels: enhancement

#355 Improved API docs.
  src/buffer/immutable.rs
  src/buffer/mod.rs
  src/buffer/mutable.rs
Labels: documentation

#352 Bumped to parquet2 v0.4
  Cargo.toml
  arrow-parquet-integration-testing/src/main.rs
  examples/parquet_read.rs
  examples/parquet_read_parallel.rs
  examples/parquet_write.rs
  examples/parquet_write_record.rs
  src/io/parquet/read/binary/basic.rs
  src/io/parquet/read/binary/dictionary.rs
  src/io/parquet/read/binary/nested.rs
  src/io/parquet/read/boolean/basic.rs
  src/io/parquet/read/boolean/nested.rs
  src/io/parquet/read/fixed_size_binary.rs
  src/io/parquet/read/mod.rs
  src/io/parquet/read/primitive/basic.rs
  src/io/parquet/read/primitive/dictionary.rs
  src/io/parquet/read/primitive/nested.rs
  src/io/parquet/read/record_batch.rs
  src/io/parquet/read/utils.rs
  src/io/parquet/write/mod.rs
  src/io/parquet/write/record_batch.rs
  src/io/parquet/write/stream.rs
  tests/it/compute/cast.rs
  tests/it/io/parquet/mod.rs
Labels: enhancement

#358 Added more docs.
  src/alloc/mod.rs
  src/array/binary/from.rs
  src/array/binary/mutable.rs
  src/array/boolean/mutable.rs
  src/array/dictionary/mutable.rs
  src/array/ffi.rs
  src/array/fixed_size_binary/mod.rs
  src/array/fixed_size_binary/mutable.rs
  src/array/fixed_size_list/mod.rs
  src/array/list/iterator.rs
  src/array/mod.rs
  src/array/null.rs
  src/array/specification.rs
  src/array/struct_.rs
  src/array/utf8/iterator.rs
  src/bitmap/mod.rs
  src/bitmap/mutable.rs
  src/bitmap/utils/chunk_iterator/chunks_exact.rs
  src/bitmap/utils/chunk_iterator/mod.rs
  src/bitmap/utils/iterator.rs
  src/bitmap/utils/mod.rs
  src/bitmap/utils/slice_iterator.rs
  src/bitmap/utils/zip_validity.rs
  src/buffer/immutable.rs
  src/buffer/mod.rs
  src/buffer/mutable.rs
  src/datatypes/field.rs
  src/datatypes/mod.rs
  src/error.rs
  src/io/ipc/mod.rs
  src/io/ipc/read/mod.rs
  src/io/ipc/write/common.rs
  src/io/ipc/write/mod.rs
  src/io/mod.rs
  src/io/parquet/mod.rs
  src/io/parquet/read/mod.rs
  src/io/parquet/write/mod.rs
  src/io/print.rs
  src/lib.rs
  src/scalar/mod.rs
  src/trusted_len.rs
  src/types/bit_chunk.rs
  src/types/index.rs
  src/types/mod.rs
  src/types/simd/mod.rs
  src/util/bench_util.rs
  src/util/mod.rs
Labels: documentation

#359 Added support for `Extension` (logical) type
  README.md
  examples/extension.rs
  guide/src/SUMMARY.md
  guide/src/extension.md
  src/array/dictionary/mod.rs
  src/array/display.rs
  src/array/fixed_size_binary/mod.rs
  src/array/fixed_size_binary/mutable.rs
  src/array/fixed_size_list/mod.rs
  src/array/list/mod.rs
  src/array/struct_.rs
  src/array/union/mod.rs
  src/datatypes/field.rs
  src/datatypes/mod.rs
  src/ffi/schema.rs
  src/io/ipc/convert.rs
  src/io/ipc/mod.rs
  src/io/json_integration/read.rs
  src/io/json_integration/schema.rs
  src/scalar/mod.rs
  tests/it/array/fixed_size_binary/mutable.rs
  tests/it/io/ipc/common.rs
  tests/it/io/ipc/read/file.rs
  tests/it/io/ipc/read/stream.rs
  tests/it/io/ipc/write/file.rs
  tests/it/io/ipc/write/stream.rs
  tests/it/io/parquet/mod.rs
Labels: feature

#278 Made IPC integration tests run tests that are not run by arrow-rs
  .github/workflows/integration-ipc.yml
  integration-testing/Cargo.toml
  integration-testing/unskip.patch
Labels: testing

#268 Added support for MONTH_DAY_NANO interval type
  integration-testing/unskip.patch
  src/array/display.rs
  src/array/equal/mod.rs
  src/array/mod.rs
  src/array/primitive/mod.rs
  src/compute/aggregate/memory.rs
  src/compute/filter.rs
  src/compute/take/mod.rs
  src/datatypes/mod.rs
  src/datatypes/physical_type.rs
  src/ffi/array.rs
  src/ffi/schema.rs
  src/io/ipc/convert.rs
  src/io/ipc/gen/Schema.rs
  src/io/ipc/read/deserialize.rs
  src/io/ipc/write/serialize.rs
  src/io/json_integration/read.rs
  src/io/json_integration/schema.rs
  src/scalar/equal.rs
  src/scalar/mod.rs
  src/types/mod.rs
  tests/it/array/primitive/mod.rs
Labels: feature
