Repository jorgecarleitao/arrow2, pull requests merged in 2021-12, with the labels that each got.

#648 Simplified Primitive and Boolean scalar
  .github/workflows/security.yml
  .github/workflows/test.yml
  src/compute/comparison/mod.rs
  src/scalar/boolean.rs
  src/scalar/primitive.rs
  tests/it/scalar/boolean.rs
  tests/it/scalar/primitive.rs
Labels: backwards-incompatible

#653 Fixed filter of predicate with validity
  src/compute/filter.rs
  tests/it/compute/filter.rs
Labels: bug

#657 Fixed performance regression of CSV reading
  src/io/csv/read/deserialize.rs
  src/io/csv/read_async/deserialize.rs
  src/io/csv/read_utils.rs
Labels: bug

#658 Added example to read parquet in parallel with rayon
  examples/parquet_read_parallel.rs
  examples/parquet_read_parallel/Cargo.toml
  examples/parquet_read_parallel/src/main.rs
  examples/parquet_read_record.rs
Labels: documentation

#660 Simplified `Utf8Scalar` and `BinaryScalar`
  src/compute/comparison/mod.rs
  src/scalar/binary.rs
  src/scalar/utf8.rs
  tests/it/scalar/binary.rs
  tests/it/scalar/utf8.rs
Labels: backwards-incompatible

#665 Fixed error in trait constraint in compute
  src/compute/arithmetics/basic/add.rs
  src/compute/arithmetics/basic/div.rs
  src/compute/arithmetics/basic/mod.rs
  src/compute/arithmetics/basic/mul.rs
  src/compute/arithmetics/basic/pow.rs
  src/compute/arithmetics/basic/rem.rs
  src/compute/arithmetics/basic/sub.rs
  src/compute/arithmetics/mod.rs
Labels: bug

#670 Improved performance of reading utf8 required from parquet (-15%)
  benches/read_parquet.rs
  parquet_integration/write_parquet.py
  src/io/parquet/read/binary/basic.rs
  src/io/parquet/read/utils.rs
Labels: enhancement

#672 Bumped nightly in CI
  .github/workflows/security.yml
  .github/workflows/test.yml
Labels: testing

#671 Simplified trait bounds in arithmetics
  src/compute/arithmetics/basic/add.rs
  src/compute/arithmetics/basic/div.rs
  src/compute/arithmetics/basic/mul.rs
  src/compute/arithmetics/basic/pow.rs
Labels: enhancement

#674 Added integration tests for other compressions with parquet from pyarrow
  parquet_integration/write_parquet.py
  tests/it/io/parquet/read.rs
Labels: testing

#675 Made IPC ZSTD-compressed consumable by pyarrow
  src/io/ipc/compression.rs
Labels: bug

#678 Made IPC reader less restrictive
  src/io/ipc/read/reader.rs
Labels: bug, enhancement

#680 Made `dyn Array` and `Scalar` usable in `#[derive(PartialEq)]`
  src/array/equal/mod.rs
  src/scalar/equal.rs
  tests/it/array/mod.rs
  tests/it/scalar/mod.rs
Labels: enhancement

#681 DRY code via macro
  src/compute/comparison/mod.rs
Labels: enhancement

#620 Added support for `async` read of Avro
  Cargo.toml
  examples/avro_read_async.rs
  guide/src/SUMMARY.md
  guide/src/io/README.md
  guide/src/io/avro_read.md
  src/io/avro/read/block.rs
  src/io/avro/read/decompress.rs
  src/io/avro/read/deserialize.rs
  src/io/avro/read/mod.rs
  src/io/avro/read/schema.rs
  src/io/avro/read_async/block.rs
  src/io/avro/read_async/header.rs
  src/io/avro/read_async/metadata.rs
  src/io/avro/read_async/mod.rs
  src/io/avro/read_async/utils.rs
  tests/it/io/avro/read_async.rs
Labels: feature

#682 Fixed error in dispatching scalar arithmetics
  src/compute/arithmetics/mod.rs
  tests/it/compute/arithmetics/mod.rs
Labels: bug

#683 Support parquet read from dictionary-encoded nonoptional pages
  src/io/parquet/read/fixed_size_binary.rs
  tests/it/io/parquet/read.rs
Labels: feature

#688 Do not write validity without nulls in IPC
  src/io/ipc/write/serialize.rs
Labels: enhancement

#685 Added dynamic version of negation
  src/compute/arithmetics/mod.rs
  src/types/mod.rs
  tests/it/compute/arithmetics/mod.rs
Labels: feature

#689 Added `MutablePrimitiveArray::extend_constant`
  src/array/primitive/mutable.rs
  tests/it/array/primitive/mutable.rs
Labels: enhancement

#692 Migrated from `avro-rs` to `avro-schema`
  Cargo.toml
  src/io/avro/mod.rs
  src/io/avro/read/deserialize.rs
  src/io/avro/read/header.rs
  src/io/avro/read/mod.rs
  src/io/avro/read/schema.rs
  src/io/avro/read/util.rs
  src/io/avro/read_async/metadata.rs
  tests/it/io/avro/read.rs
Labels: enhancement

#694 Replaced `Display` by `Debug` for `Array`
  examples/csv_read_async.rs
  examples/parquet_read.rs
  src/array/boolean/mod.rs
  src/array/dictionary/mod.rs
  src/array/fixed_size_binary/mod.rs
  src/array/fixed_size_list/mod.rs
  src/array/list/mod.rs
  src/array/mod.rs
  src/array/null.rs
  src/array/primitive/display.rs
  src/array/primitive/mod.rs
  src/array/primitive/mutable.rs
  src/array/struct_/mod.rs
  src/array/union/mod.rs
  src/array/utf8/mod.rs
  src/compute/aggregate/min_max.rs
  src/compute/aggregate/sum.rs
  src/compute/if_then_else.rs
  src/compute/nullif.rs
  src/datatypes/field.rs
  src/datatypes/mod.rs
  src/datatypes/schema.rs
  src/io/csv/write/serialize.rs
  src/io/parquet/write/dictionary.rs
  src/scalar/equal.rs
  src/scalar/primitive.rs
  tests/it/array/boolean/mod.rs
  tests/it/array/fixed_size_binary/mod.rs
  tests/it/array/list/mod.rs
  tests/it/array/primitive/mod.rs
  tests/it/array/union.rs
  tests/it/temporal_conversions.rs
Labels: backwards-incompatible

#695 Cleaned up trait usage and added forbid_unsafe to parts
  src/array/map/mod.rs
  src/io/avro/mod.rs
  src/io/csv/mod.rs
  src/io/csv/write/serialize.rs
  src/io/ipc/read/array/binary.rs
  src/io/ipc/read/array/utf8.rs
  src/io/json/mod.rs
Labels: enhancement

#697 Removed requirement of `use Array` to access primitives' `data_type`
  examples/csv_write_parallel.rs
  examples/parquet_write_record.rs
  src/array/equal/primitive.rs
  src/array/primitive/mod.rs
  src/compute/arithmetics/basic/add.rs
  src/compute/arithmetics/basic/mod.rs
  src/compute/arithmetics/basic/mul.rs
  src/compute/arithmetics/basic/pow.rs
  src/compute/arithmetics/basic/sub.rs
  src/compute/arithmetics/decimal/add.rs
  src/compute/arithmetics/decimal/div.rs
  src/compute/arithmetics/decimal/mul.rs
  src/compute/arithmetics/decimal/sub.rs
  src/compute/arithmetics/time.rs
  src/compute/bitwise.rs
  src/compute/sort/primitive/sort.rs
Labels: enhancement

#696 Simplified most traits
  src/array/binary/mod.rs
  src/array/dictionary/ffi.rs
  src/array/dictionary/mod.rs
  src/array/growable/dictionary.rs
  src/array/list/ffi.rs
  src/array/list/mod.rs
  src/array/mod.rs
  src/array/primitive/from_natural.rs
  src/array/primitive/mod.rs
  src/array/primitive/mutable.rs
  src/array/specification.rs
  src/compute/arithmetics/basic/div.rs
  src/compute/arithmetics/basic/rem.rs
  src/compute/cast/boolean_to.rs
  src/compute/cast/dictionary_to.rs
  src/compute/cast/primitive_to.rs
  src/compute/length.rs
  src/compute/sort/boolean.rs
  src/compute/sort/common.rs
  src/compute/sort/lex_sort.rs
  src/compute/sort/mod.rs
  src/compute/temporal.rs
  src/datatypes/mod.rs
  src/datatypes/physical_type.rs
  src/io/csv/read_utils.rs
  src/io/ipc/read/array/dictionary.rs
  src/io/json/read/deserialize.rs
  src/io/json_integration/read.rs
  src/io/parquet/read/binary/basic.rs
  src/io/parquet/read/binary/dictionary.rs
  src/io/parquet/read/primitive/dictionary.rs
  src/io/parquet/write/binary/basic.rs
  src/scalar/primitive.rs
  src/types/bit_chunk.rs
  src/types/index.rs
  src/types/mod.rs
  src/types/native.rs
  src/types/offset.rs
Labels: backwards-incompatible

#690 Added support to write to Avro
  Cargo.toml
  examples/avro_write.rs
  guide/src/SUMMARY.md
  guide/src/io/avro_write.md
  src/io/avro/mod.rs
  src/io/avro/read/block.rs
  src/io/avro/read/mod.rs
  src/io/avro/read/schema.rs
  src/io/avro/read_async/metadata.rs
  src/io/avro/write/block.rs
  src/io/avro/write/header.rs
  src/io/avro/write/mod.rs
  src/io/avro/write/schema.rs
  src/io/avro/write/serialize.rs
  src/io/avro/write/util.rs
  src/io/csv/write/mod.rs
  src/io/csv/write/serialize.rs
  src/io/iterator.rs
  src/io/mod.rs
  tests/it/io/avro/mod.rs
  tests/it/io/avro/read.rs
  tests/it/io/avro/read_async.rs
  tests/it/io/avro/write.rs
Labels: feature

#698 Made Avro read API use `Block` and `CompressedBlock`
  examples/avro_read_async.rs
  src/io/avro/mod.rs
  src/io/avro/read/block.rs
  src/io/avro/read/decompress.rs
  src/io/avro/read/deserialize.rs
  src/io/avro/read/mod.rs
  src/io/avro/read_async/block.rs
  src/io/avro/read_async/mod.rs
  src/io/avro/write/block.rs
  src/io/avro/write/mod.rs
  tests/it/io/avro/read_async.rs
Labels: backwards-incompatible

#701 Added more conversions from parquet
  parquet_integration/write_parquet.py
  src/io/parquet/read/mod.rs
  src/io/parquet/read/schema/metadata.rs
  tests/it/io/parquet/mod.rs
  tests/it/io/parquet/read.rs
Labels: feature

#699 Added support for compressed Avro write
  Cargo.toml
  examples/avro_write.rs
  src/io/avro/read/decompress.rs
  src/io/avro/write/block.rs
  src/io/avro/write/compress.rs
  src/io/avro/write/mod.rs
  tests/it/io/avro/write.rs
Labels: feature

#704 Fixed typo in reading RLE-encoded parquet
  src/io/parquet/read/binary/basic.rs
Labels: bug

#705 Replaced Display by Debug in `Utf8Array`
  src/array/utf8/mod.rs
Labels: bug, no-changelog

#706 Refactored JSON read to split IO-bounded from CPU-bounded tasks
  examples/json_read.rs
  guide/src/SUMMARY.md
  guide/src/io/json_read.md
  src/io/json/mod.rs
  src/io/json/read/deserialize.rs
  src/io/json/read/infer_schema.rs
  src/io/json/read/iterator.rs
  src/io/json/read/mod.rs
  src/io/json/read/reader.rs
  src/io/json/read/util.rs
  tests/it/io/json/mod.rs
  tests/it/io/json/read.rs
Labels: feature

#711 Moved is_ordered from `Field` to `DataType::Dictionary`
  arrow-parquet-integration-testing/src/main.rs
  src/array/dictionary/mod.rs
  src/array/dictionary/mutable.rs
  src/array/display.rs
  src/array/ord.rs
  src/compute/arithmetics/mod.rs
  src/compute/cast/dictionary_to.rs
  src/compute/cast/mod.rs
  src/compute/sort/mod.rs
  src/compute/take/mod.rs
  src/datatypes/field.rs
  src/datatypes/mod.rs
  src/ffi/ffi.rs
  src/ffi/schema.rs
  src/io/avro/read/nested.rs
  src/io/avro/read/schema.rs
  src/io/csv/write/serialize.rs
  src/io/ipc/convert.rs
  src/io/ipc/read/common.rs
  src/io/ipc/write/common.rs
  src/io/ipc/write/serialize.rs
  src/io/json/read/deserialize.rs
  src/io/json_integration/mod.rs
  src/io/json_integration/schema.rs
  src/io/parquet/read/mod.rs
  src/io/parquet/read/primitive/mod.rs
  src/io/parquet/write/mod.rs
  src/io/parquet/write/schema.rs
  src/scalar/equal.rs
  tests/it/compute/cast.rs
  tests/it/ffi.rs
  tests/it/io/avro/read.rs
  tests/it/io/json/mod.rs
  tests/it/io/parquet/mod.rs
  tests/it/io/print.rs
Labels: backwards-incompatible

#713 Moved dict_id to IPC-specific IO
  arrow-parquet-integration-testing/src/main.rs
  examples/extension.rs
  examples/ipc_file_write.rs
  examples/json_read.rs
  integration-testing/src/bin/arrow-file-to-stream.rs
  integration-testing/src/bin/arrow-json-integration-test.rs
  integration-testing/src/bin/arrow-stream-to-file.rs
  integration-testing/src/flight_client_scenarios/integration_test.rs
  integration-testing/src/flight_server_scenarios/integration_test.rs
  integration-testing/src/lib.rs
  src/columns.rs
  src/datatypes/field.rs
  src/io/flight/mod.rs
  src/io/ipc/convert.rs
  src/io/ipc/mod.rs
  src/io/ipc/read/array/dictionary.rs
  src/io/ipc/read/array/fixed_size_list.rs
  src/io/ipc/read/array/list.rs
  src/io/ipc/read/array/map.rs
  src/io/ipc/read/array/struct_.rs
  src/io/ipc/read/array/union.rs
  src/io/ipc/read/common.rs
  src/io/ipc/read/deserialize.rs
  src/io/ipc/read/mod.rs
  src/io/ipc/read/reader.rs
  src/io/ipc/read/schema.rs
  src/io/ipc/read/stream.rs
  src/io/ipc/write/common.rs
  src/io/ipc/write/mod.rs
  src/io/ipc/write/schema.rs
  src/io/ipc/write/stream.rs
  src/io/ipc/write/stream_async.rs
  src/io/ipc/write/writer.rs
  src/io/json_integration/mod.rs
  src/io/json_integration/read/array.rs
  src/io/json_integration/read/mod.rs
  src/io/json_integration/read/schema.rs
  src/io/json_integration/write/array.rs
  src/io/json_integration/write/mod.rs
  src/io/json_integration/write/schema.rs
  src/io/parquet/read/schema/metadata.rs
  src/io/parquet/write/schema.rs
  src/lib.rs
  src/record_batch.rs
  tests/it/io/ipc/common.rs
  tests/it/io/ipc/read/file.rs
  tests/it/io/ipc/read/stream.rs
  tests/it/io/ipc/write/file.rs
  tests/it/io/ipc/write/stream.rs
  tests/it/io/ipc/write_async.rs
  tests/it/io/parquet/mod.rs
Labels: backwards-incompatible

#715 Removed `Option` from fields' metadata
  examples/metadata.rs
  src/datatypes/field.rs
  src/datatypes/mod.rs
  src/ffi/schema.rs
  src/io/avro/read/schema.rs
  src/io/ipc/read/schema.rs
  src/io/ipc/write/schema.rs
  src/io/json_integration/read/schema.rs
  src/io/json_integration/write/schema.rs
Labels: backwards-incompatible

#720 Fixed error in writing json as array
  src/io/json/write/serialize.rs
  tests/it/io/json/mod.rs
  tests/it/io/json/write.rs
Labels: bug, no-changelog

#721 Fixed error in compare booleans
  src/compute/comparison/boolean.rs
  tests/it/compute/comparison.rs
Labels: bug
