Repository jorgecarleitao/arrow2, pull requests merged in 2021-11, with the labels that each got.

#563 Made bitmap not cache null count
  src/bitmap/immutable.rs
Labels: enhancement

#565 Added ffi support for `FixedSizeList` and `FixedSizeBinary`
  arrow-pyarrow-integration-testing/tests/test_sql.py
  src/array/binary/ffi.rs
  src/array/boolean/ffi.rs
  src/array/dictionary/ffi.rs
  src/array/ffi.rs
  src/array/fixed_size_binary/ffi.rs
  src/array/fixed_size_list/ffi.rs
  src/array/list/ffi.rs
  src/array/list/mutable.rs
  src/array/map/ffi.rs
  src/array/primitive/ffi.rs
  src/array/union/ffi.rs
  src/array/utf8/ffi.rs
  src/ffi/array.rs
  src/ffi/ffi.rs
  src/ffi/schema.rs
  tests/it/ffi.rs
Labels: feature

#566 Added writing of compressed Arrow IPC (feather)
  src/io/ipc/compression.rs
  src/io/ipc/read/array/boolean.rs
  src/io/ipc/read/array/dictionary.rs
  src/io/ipc/read/deserialize.rs
  src/io/ipc/read/read_basic.rs
  src/io/ipc/write/common.rs
  src/io/ipc/write/mod.rs
  src/io/ipc/write/serialize.rs
  tests/it/io/ipc/write/file.rs
  tests/it/io/ipc/write/stream.rs
Labels: feature

#544 Made example of parallel parquet write be over multiple batches
  examples/parquet_write_parallel/src/main.rs
Labels: documentation

#575 Simplified IPC stream writer / remove finish on drop from stream writer
  src/io/ipc/write/stream.rs
Labels: backwards-incompatible

#572 Simplified trait in compute.
  src/compute/arithmetics/basic/add.rs
  src/compute/arithmetics/basic/div.rs
  src/compute/arithmetics/basic/mul.rs
  src/compute/arithmetics/basic/rem.rs
  src/compute/arithmetics/basic/sub.rs
  src/compute/arithmetics/mod.rs
Labels: backwards-incompatible

#576 Simplified IPC APIs
  examples/extension.rs
  examples/ipc_file_write.rs
  integration-testing/src/bin/arrow-file-to-stream.rs
  integration-testing/src/bin/arrow-json-integration-test.rs
  integration-testing/src/bin/arrow-stream-to-file.rs
  integration-testing/src/flight_client_scenarios/integration_test.rs
  integration-testing/src/flight_server_scenarios/auth_basic_proto.rs
  integration-testing/src/flight_server_scenarios/integration_test.rs
  src/io/flight/mod.rs
  src/io/ipc/mod.rs
  src/io/ipc/write/common.rs
  src/io/ipc/write/mod.rs
  src/io/ipc/write/schema.rs
  src/io/ipc/write/stream.rs
  src/io/ipc/write/writer.rs
  src/io/parquet/write/schema.rs
  tests/it/io/ipc/write/file.rs
  tests/it/io/ipc/write/stream.rs
Labels: backwards-incompatible

#577 Added support to write Arrow IPC streams asynchronously
  Cargo.toml
  README.md
  src/io/flight/mod.rs
  src/io/ipc/write/common.rs
  src/io/ipc/write/common_async.rs
  src/io/ipc/write/common_sync.rs
  src/io/ipc/write/mod.rs
  src/io/ipc/write/stream.rs
  src/io/ipc/write/stream_async.rs
  src/io/ipc/write/writer.rs
  tests/it/io/ipc/mod.rs
  tests/it/io/ipc/write_async.rs
Labels: feature

#578 Improved performance of `bitmap::from_trusted` (3x)
  benches/bitmap.rs
  src/bitmap/mutable.rs
  tests/it/bitmap/mutable.rs
Labels: enhancement

#584 Simplified dictionary indexes
  src/array/dictionary/mod.rs
  src/array/dictionary/mutable.rs
  src/array/display.rs
  src/array/equal/mod.rs
  src/array/ffi.rs
  src/array/growable/mod.rs
  src/array/mod.rs
  src/array/ord.rs
  src/compute/aggregate/memory.rs
  src/compute/cast/dictionary_to.rs
  src/compute/cast/mod.rs
  src/compute/sort/mod.rs
  src/compute/take/mod.rs
  src/datatypes/mod.rs
  src/datatypes/physical_type.rs
  src/ffi/array.rs
  src/ffi/bridge.rs
  src/ffi/schema.rs
  src/io/avro/read/nested.rs
  src/io/avro/read/schema.rs
  src/io/csv/write/serialize.rs
  src/io/ipc/convert.rs
  src/io/ipc/read/deserialize.rs
  src/io/ipc/write/common.rs
  src/io/ipc/write/serialize.rs
  src/io/json/read/deserialize.rs
  src/io/json_integration/mod.rs
  src/io/json_integration/read.rs
  src/io/json_integration/schema.rs
  src/io/parquet/read/mod.rs
  src/io/parquet/write/mod.rs
  src/types/mod.rs
  tests/it/compute/cast.rs
  tests/it/ffi.rs
  tests/it/io/avro/read/mod.rs
  tests/it/io/csv/write.rs
  tests/it/io/json/mod.rs
  tests/it/io/print.rs
Labels: backwards-incompatible

#587 Support dictionaries in nested types over IPC
  integration-testing/src/flight_client_scenarios/integration_test.rs
  integration-testing/src/flight_server_scenarios/integration_test.rs
  integration-testing/unskip.patch
  src/array/dictionary/mod.rs
  src/array/display.rs
  src/datatypes/field.rs
  src/datatypes/schema.rs
  src/io/flight/mod.rs
  src/io/ipc/convert.rs
  src/io/ipc/read/array/binary.rs
  src/io/ipc/read/array/boolean.rs
  src/io/ipc/read/array/dictionary.rs
  src/io/ipc/read/array/fixed_size_binary.rs
  src/io/ipc/read/array/fixed_size_list.rs
  src/io/ipc/read/array/list.rs
  src/io/ipc/read/array/map.rs
  src/io/ipc/read/array/null.rs
  src/io/ipc/read/array/primitive.rs
  src/io/ipc/read/array/struct_.rs
  src/io/ipc/read/array/union.rs
  src/io/ipc/read/array/utf8.rs
  src/io/ipc/read/common.rs
  src/io/ipc/read/deserialize.rs
  src/io/ipc/read/reader.rs
  src/io/ipc/read/stream.rs
  src/io/ipc/write/common.rs
  src/io/ipc/write/stream.rs
  src/io/json_integration/mod.rs
  src/io/json_integration/read.rs
  src/scalar/dictionary.rs
  src/scalar/equal.rs
  src/scalar/mod.rs
  tests/it/io/ipc/read/file.rs
  tests/it/io/ipc/write/file.rs
Labels: feature

#591 Added more tests.
  src/array/binary/mutable.rs
  tests/it/array/binary/mutable.rs
Labels: testing

#593 Fixed error in compressing IPC LZ4
  src/io/ipc/compression.rs
Labels: bug

#595 Mitigated `RUSTSEC-2020-0159`
  .cargo/audit.toml
  .github/workflows/security.yml
  tests/it/io/ipc/write/file.rs
  tests/it/test_util.rs
Labels: testing

#596 Fixed error in computing projection in `io::ipc::read::reader::FileReader`
  src/io/ipc/read/reader.rs
  tests/it/io/ipc/read/file.rs
Labels: bug

#597 Optimized `MutableBinaryArray`
  src/array/binary/mutable.rs
Labels: enhancement

#599 Added `len` to every array
  src/array/binary/iterator.rs
  src/array/binary/mod.rs
  src/array/boolean/mod.rs
  src/array/dictionary/iterator.rs
  src/array/dictionary/mod.rs
  src/array/equal/boolean.rs
  src/array/fixed_size_binary/mod.rs
  src/array/fixed_size_list/mod.rs
  src/array/list/mod.rs
  src/array/map/mod.rs
  src/array/null.rs
  src/array/primitive/mod.rs
  src/array/struct_.rs
  src/array/union/iterator.rs
  src/array/union/mod.rs
  src/array/utf8/iterator.rs
  src/array/utf8/mod.rs
  src/compute/arity.rs
  src/compute/boolean_kleene.rs
  src/compute/sort/binary.rs
  src/compute/sort/boolean.rs
  src/compute/sort/primitive/indices.rs
  src/compute/take/generic_binary.rs
  src/compute/take/list.rs
  src/lib.rs
Labels: enhancement

#600 Improved performance of `is_not_null`.
  src/compute/boolean.rs
Labels: enhancement

#601 Added more tests
  src/array/fixed_size_binary/mod.rs
  src/array/list/mutable.rs
  tests/it/array/boolean/mod.rs
  tests/it/array/fixed_size_binary/mod.rs
  tests/it/array/list/mutable.rs
Labels: testing

#598 Added support for `NullArray` at FFI.
  arrow-pyarrow-integration-testing/tests/test_sql.py
  src/array/null.rs
  src/ffi/array.rs
  src/io/parquet/read/mod.rs
Labels: enhancement

#603 Simplified traits and added documentation
  src/compute/aggregate/min_max.rs
  src/compute/arithmetics/basic/add.rs
  src/compute/arithmetics/basic/div.rs
  src/compute/arithmetics/basic/mul.rs
  src/compute/arithmetics/basic/rem.rs
  src/compute/arithmetics/basic/sub.rs
  src/compute/arithmetics/decimal/add.rs
  src/compute/arithmetics/decimal/div.rs
  src/compute/arithmetics/decimal/mul.rs
  src/compute/arithmetics/decimal/sub.rs
  src/compute/arithmetics/mod.rs
  src/compute/bitwise.rs
  src/compute/hash.rs
  src/compute/mod.rs
Labels: enhancement

#602 Added support to read decimal from csv
  src/io/csv/read_utils.rs
  tests/it/io/csv/read.rs
Labels: feature

#604 Refactored comparison `Operator`
  src/array/utf8/mod.rs
  src/compute/comparison/binary.rs
  src/compute/comparison/boolean.rs
  src/compute/comparison/mod.rs
  src/compute/comparison/primitive.rs
  src/compute/comparison/utf8.rs
  src/compute/regex_match.rs
  src/compute/sort/utf8.rs
  tests/it/compute/comparison.rs
Labels: backwards-incompatible

#605 Improved performance of decimal arithmetics
  src/compute/arithmetics/decimal/add.rs
  src/compute/arithmetics/decimal/div.rs
  src/compute/arithmetics/decimal/mod.rs
  src/compute/arithmetics/decimal/mul.rs
  src/compute/arithmetics/decimal/sub.rs
Labels: enhancement

#610 Speed up boolean comparison kernels (~3x)
  benches/comparison_kernels.rs
  src/compute/comparison/boolean.rs
Labels: feature

#611 Removed most of allocations in IPC reading
  src/io/ipc/read/reader.rs
  src/io/ipc/read/stream.rs
Labels: enhancement

#612 Added support to read snappy-compressed Avro
  Cargo.toml
  src/io/avro/mod.rs
  src/io/avro/read/mod.rs
  src/io/avro/read/util.rs
  tests/it/io/avro/read/mod.rs
Labels: feature

#547 Added support to read struct arrays from parquet
  Cargo.toml
  examples/parquet_read.rs
  examples/parquet_read_parallel.rs
  parquet_integration/write_parquet.py
  src/io/parquet/read/README.md
  src/io/parquet/read/binary/basic.rs
  src/io/parquet/read/binary/mod.rs
  src/io/parquet/read/binary/nested.rs
  src/io/parquet/read/boolean/basic.rs
  src/io/parquet/read/boolean/mod.rs
  src/io/parquet/read/boolean/nested.rs
  src/io/parquet/read/mod.rs
  src/io/parquet/read/nested_utils.rs
  src/io/parquet/read/primitive/mod.rs
  src/io/parquet/read/record_batch.rs
  src/io/parquet/write/binary/basic.rs
  tests/it/io/parquet/mod.rs
  tests/it/io/parquet/read.rs
Labels: feature

#614 Added support to read Avro files' metadata asynchronously
  Cargo.toml
  src/io/avro/mod.rs
  src/io/avro/read/block.rs
  src/io/avro/read/decompress.rs
  src/io/avro/read/header.rs
  src/io/avro/read/mod.rs
  src/io/avro/read/util.rs
  src/io/avro/read_async/header.rs
  src/io/avro/read_async/mod.rs
  tests/it/io/avro/mod.rs
  tests/it/io/avro/read.rs
  tests/it/io/avro/read_async.rs
Labels: feature

#617 Made `MutableArray` `Send + Sync`
  src/array/mod.rs
Labels: enhancement

#618 Bumped `confy-table`
  Cargo.toml
Labels: enhancement

#619 Simplified example
  examples/s3/Cargo.toml
  examples/s3/src/main.rs
  examples/s3/src/stream.rs
Labels: documentation

#621 Sealed 2 traits to forbid downstream implementations
  src/array/specification.rs
  src/io/parquet/write/levels.rs
  src/types/mod.rs
Labels: backwards-incompatible

#623 Added support to write timestamps with timezones.
  src/io/csv/write/serialize.rs
  src/temporal_conversions.rs
  tests/it/io/csv/write.rs
Labels: feature

#625 Fixed error in union FFI
  .github/workflows/integration-ffi.yml
  arrow-pyarrow-integration-testing/tests/test_sql.py
  src/array/union/ffi.rs
Labels: bug

#628 Removed unneeded trait.
  src/io/ipc/read/reader.rs
  src/record_batch.rs
Labels: backwards-incompatible

#631 Fixed error in reading nullable from Avro.
  examples/avro_read.rs
  examples/csv_read_async.rs
  examples/growable.rs
  examples/parquet_read_parallel.rs
  src/io/avro/read/deserialize.rs
Labels: bug

#632 Improved error message for missing feature in compressed parquet
  Cargo.toml
  src/io/parquet/mod.rs
Labels: enhancement

#633 Faster `take` with null values (2-3x)
  benches/take_kernels.rs
  src/compute/take/boolean.rs
  src/compute/take/generic_binary.rs
  src/compute/take/primitive.rs
Labels: enhancement

#634 Split "compute" feature
  .github/workflows/test.yml
  Cargo.toml
  benches/concatenate.rs
  src/compute/arithmetics/basic/common.rs
  src/compute/arithmetics/basic/div.rs
  src/compute/arithmetics/basic/mod.rs
  src/compute/arithmetics/decimal/add.rs
  src/compute/arithmetics/decimal/div.rs
  src/compute/arithmetics/decimal/mul.rs
  src/compute/arithmetics/decimal/sub.rs
  src/compute/arity.rs
  src/compute/concatenate.rs
  src/compute/contains.rs
  src/compute/if_then_else.rs
  src/compute/like.rs
  src/compute/mod.rs
  src/compute/nullif.rs
  src/compute/utils.rs
  src/compute/window.rs
  src/lib.rs
  tests/it/compute/concatenate.rs
  tests/it/compute/mod.rs
  tests/it/main.rs
Labels: backwards-incompatible

#637 Use `DynComparator` for `lexsort` and `partition`
  src/compute/partition.rs
  src/compute/sort/lex_sort.rs
  src/compute/sort/mod.rs
Labels: backwards-incompatible

#636 Cleaned up benches
  Cargo.toml
  benches/aggregate.rs
  benches/arithmetic_kernels.rs
  benches/bitmap.rs
  benches/bitmap_ops.rs
  benches/bitwise.rs
  benches/cast_kernels.rs
  benches/comparison_kernels.rs
  benches/concatenate.rs
  benches/count_zeros.rs
  benches/filter_kernels.rs
  benches/from_trusted_len_iter.rs
  benches/growable.rs
  benches/hash_kernel.rs
  benches/iter_list.rs
  benches/iter_utf8.rs
  benches/length_kernel.rs
  benches/sort_kernel.rs
  benches/take_kernels.rs
  benches/unset_count.rs
  benches/write_csv.rs
  benches/write_ipc.rs
  benches/write_parquet.rs
  src/util/bench_util.rs
Labels: testing

#640 Simplified `ArrowError`
  src/array/binary/mutable.rs
  src/array/dictionary/mutable.rs
  src/array/fixed_size_list/mutable.rs
  src/array/list/mutable.rs
  src/array/utf8/mutable.rs
  src/compute/cast/dictionary_to.rs
  src/datatypes/field.rs
  src/datatypes/schema.rs
  src/error.rs
  src/ffi/ffi.rs
  src/ffi/schema.rs
  src/io/avro/read/decompress.rs
  src/io/avro/read/nested.rs
  src/io/flight/mod.rs
  src/io/ipc/compression.rs
  src/io/ipc/read/array/dictionary.rs
  src/io/ipc/read/common.rs
  src/io/ipc/read/read_basic.rs
  src/io/ipc/read/reader.rs
  src/io/ipc/read/stream.rs
  src/io/ipc/write/common_async.rs
  src/io/ipc/write/common_sync.rs
  src/io/ipc/write/stream.rs
  src/io/ipc/write/stream_async.rs
  src/io/ipc/write/writer.rs
  src/io/json/read/infer_schema.rs
  src/io/json/read/reader.rs
  src/io/json_integration/read.rs
  src/io/json_integration/schema.rs
  src/io/parquet/read/schema/metadata.rs
  src/io/parquet/read/statistics/fixlen.rs
  tests/it/io/json/read.rs
Labels: backwards-incompatible

#643 Made API to create field accept `String`
  src/datatypes/field.rs
  src/datatypes/schema.rs
Labels: enhancement

#644 Made `Scalar: Send+Sync`
  src/scalar/mod.rs
Labels: bug

#645 Made `Filter: Send+Sync`
  src/compute/filter.rs
Labels: enhancement

#646 Improved performance in cast Primitive to Binary/String (2x)
  benches/cast_kernels.rs
  src/compute/cast/primitive_to.rs
Labels: enhancement
