Repository jorgecarleitao/arrow2, pull requests merged in 2021-07, with the labels that each got.

#216 Added badges to README
  README.md
Labels: documentation

#212 Fixed nested FFI.
  arrow-pyarrow-integration-testing/tests/test_sql.py
  src/ffi/array.rs
  src/ffi/ffi.rs
Labels: bug

#219 Added support for take of interval of days_ms
  src/compute/take/mod.rs
Labels: enhancement

#218 Added support for limited sort
  benches/sort_kernel.rs
  src/buffer/mutable.rs
  src/compute/merge_sort/mod.rs
  src/compute/sort/boolean.rs
  src/compute/sort/common.rs
  src/compute/sort/lex_sort.rs
  src/compute/sort/mod.rs
  src/compute/sort/primitive/indices.rs
  src/compute/sort/primitive/mod.rs
  src/compute/sort/primitive/sort.rs
  src/compute/sort/utf8.rs
Labels: backwards-incompatible, enhancement

#220 Generalized sort to accept indices other than i32.
  src/array/specification.rs
  src/compute/sort/boolean.rs
  src/compute/sort/common.rs
  src/compute/sort/lex_sort.rs
  src/compute/sort/mod.rs
  src/compute/sort/primitive/indices.rs
  src/compute/sort/utf8.rs
Labels: backwards-incompatible, enhancement

#213 Added FFI for remaining types
  arrow-pyarrow-integration-testing/tests/test_sql.py
  src/array/fixed_size_list/mod.rs
  src/ffi/array.rs
  src/ffi/ffi.rs
Labels: enhancement

#222 Add support to merge sort with a limit
  src/compute/merge_sort/mod.rs
Labels: backwards-incompatible, enhancement

#238 Simplified `new` signature of growable API
  examples/growable.rs
  src/array/growable/binary.rs
  src/array/growable/boolean.rs
  src/array/growable/fixed_binary.rs
  src/array/growable/list.rs
  src/array/growable/mod.rs
  src/array/growable/primitive.rs
  src/array/growable/structure.rs
  src/array/growable/utf8.rs
  src/compute/filter.rs
  src/compute/take/list.rs
Labels: backwards-incompatible, enhancement

#242 Added example and guide section on compute
  examples/arithmetics.rs
  guide/src/SUMMARY.md
  guide/src/compute.md
  src/compute/arithmetics/mod.rs
  src/compute/arity.rs
Labels: documentation
