Repository jorgecarleitao/arrow2, pull requests merged in 2021-09, with the labels that each got.

#368 Added `Send+Sync` to `MutableBuffer`
  src/buffer/mutable.rs
Labels: enhancement

#365 Improved performance of unary _not_ for aligned bitmaps (3x)
  Cargo.toml
  benches/bitmap_ops.rs
  src/bitmap/bitmap_ops.rs
  src/bitmap/utils/chunk_iterator/chunks_exact.rs
  src/bitmap/utils/chunk_iterator/mod.rs
Labels: enhancement

#346 Added support for compute to `BinaryArray`
  src/array/binary/from.rs
  src/array/binary/mutable.rs
  src/array/growable/binary.rs
  src/array/ord.rs
  src/compute/aggregate/min_max.rs
  src/compute/arithmetics/decimal/sub.rs
  src/compute/cast/binary_to.rs
  src/compute/cast/boolean_to.rs
  src/compute/cast/mod.rs
  src/compute/cast/primitive_to.rs
  src/compute/comparison/binary.rs
  src/compute/comparison/mod.rs
  src/compute/comparison/utf8.rs
  src/compute/contains.rs
  src/compute/like.rs
  src/compute/merge_sort/mod.rs
  src/compute/sort/binary.rs
  src/compute/sort/mod.rs
  src/compute/substring.rs
  src/io/parquet/read/binary/mod.rs
  tests/it/array/binary/mod.rs
  tests/it/array/binary/mutable.rs
  tests/it/compute/cast.rs
  tests/it/io/json/write.rs
Labels: feature

#372 Added support for `async` parquet write
  README.md
  src/io/parquet/write/stream.rs
Labels: feature

#363 Add support to extension types in FFI
  arrow-pyarrow-integration-testing/tests/test_sql.py
  src/datatypes/field.rs
  src/datatypes/mod.rs
  src/ffi/schema.rs
  src/io/ipc/convert.rs
  src/io/ipc/mod.rs
  src/io/json_integration/schema.rs
  tests/it/ffi.rs
Labels: feature

#369 Made most features not default
  .github/workflows/test.yml
  Cargo.toml
  guide/src/README.md
Labels: backwards-incompatible

#375 Fixed display of timestamp with tz.
  src/array/display.rs
  src/temporal_conversions.rs
  tests/it/array/primitive/mod.rs
  tests/it/io/print.rs
Labels: bug

#380 Added more tests.
  tests/it/array/primitive/mod.rs
  tests/it/array/primitive/mutable.rs
  tests/it/array/utf8/mod.rs
  tests/it/array/utf8/mutable.rs
Labels: testing

#378 Bumped `lexical-core`
  Cargo.toml
Labels: enhancement

#379 Simplified enums in `datatypes`
  src/compute/arithmetics/time.rs
  src/compute/cast/mod.rs
  src/compute/cast/primitive_to.rs
  src/datatypes/mod.rs
  src/temporal_conversions.rs
Labels: backwards-incompatible

#382 Improved performance of writing to CSV (20-25%)
  Cargo.toml
  benches/comparison_kernels.rs
  benches/filter_kernels.rs
  benches/sort_kernel.rs
  benches/take_kernels.rs
  benches/write_csv.rs
  benches/write_ipc.rs
  benches/write_parquet.rs
  src/io/csv/write/iterator.rs
  src/io/csv/write/mod.rs
  src/io/csv/write/serialize.rs
  src/util/bench_util.rs
  src/util/lexical.rs
Labels: enhancement

#376 Fixed casting of utf8 <> Timestamp with and without timezone
  Cargo.toml
  src/compute/cast/mod.rs
  src/compute/cast/primitive_to.rs
  src/compute/cast/timestamps.rs
  src/compute/cast/utf8_to.rs
  src/temporal_conversions.rs
  tests/it/compute/cast.rs
  tests/it/main.rs
  tests/it/temporal_conversions.rs
Labels: enhancement

#384 Fixed error in `MutableBitmap::push_unchecked`
  src/array/primitive/mutable.rs
  src/bitmap/mutable.rs
Labels: bug

#386 Made GroupFilter optional in parquet's`RecordReader` and added method to set it.
  benches/read_parquet.rs
  examples/parquet_read_record.rs
  src/io/parquet/read/record_batch.rs
  tests/it/io/parquet/mod.rs
  tests/it/io/parquet/read.rs
Labels: backwards-incompatible

#387 Moved guide examples to examples/
  examples/csv_write.rs
  examples/csv_write_parallel.rs
  guide/src/io/csv_write.md
  src/docs.rs
Labels: documentation

#388 Moved compute tests to tests/
  src/compute/boolean.rs
  src/compute/concat.rs
  src/compute/filter.rs
  src/compute/hash.rs
  src/compute/if_then_else.rs
  src/compute/sort/mod.rs
  tests/it/compute/boolean.rs
  tests/it/compute/concat.rs
  tests/it/compute/filter.rs
  tests/it/compute/hash.rs
  tests/it/compute/if_then_else.rs
  tests/it/compute/mod.rs
  tests/it/compute/sort.rs
Labels: testing

#389 Moved tests to tests/
  src/compute/boolean_kleene.rs
  src/compute/length.rs
  src/compute/like.rs
  src/compute/limit.rs
  src/compute/merge_sort/mod.rs
  src/compute/partition.rs
  src/compute/regex_match.rs
  src/compute/substring.rs
  src/compute/temporal.rs
  src/compute/window.rs
  tests/it/compute/boolean_kleene.rs
  tests/it/compute/length.rs
  tests/it/compute/like.rs
  tests/it/compute/limit.rs
  tests/it/compute/merge_sort.rs
  tests/it/compute/mod.rs
  tests/it/compute/partition.rs
  tests/it/compute/regex_match.rs
  tests/it/compute/substring.rs
  tests/it/compute/temporal.rs
  tests/it/compute/window.rs
Labels: testing

#391 Made docs be compiled with feature `full`
  .github/workflows/docs.yml
  Cargo.toml
  README.md
  src/compute/aggregate/simd/mod.rs
  src/compute/cast/primitive_to.rs
  src/compute/mod.rs
  src/io/ipc/compression.rs
  src/io/mod.rs
  src/lib.rs
  src/util/mod.rs
Labels: documentation

#394 Fix testing of SIMD
  .github/workflows/test.yml
Labels: testing

#393 Fixed error in extending `MutableBitmap`
  src/bitmap/mutable.rs
  tests/it/bitmap/mutable.rs
Labels: bug

#397 Fixed error writing dictionary extension to IPC
  src/io/ipc/convert.rs
  tests/it/io/ipc/write/file.rs
Labels: bug

#402 Added support to read dict-encoded required primitive types from parquet
  src/io/parquet/read/primitive/basic.rs
  tests/it/io/parquet/read.rs
Labels: enhancement

#403 Added tests to some invariants of `unsafe`
  src/array/binary/mod.rs
  src/array/fixed_size_binary/mod.rs
  src/array/utf8/mod.rs
  tests/it/array/binary/mod.rs
  tests/it/array/utf8/mod.rs
Labels: testing

#411 Skipped some feature permutations.
  Cargo.toml
Labels: testing

#414 Made `DynComparator` `Send+Sync`
  src/array/ord.rs
Labels: backwards-incompatible

#412 Added support to extract hours and years from timestamps with timezone
  src/compute/temporal.rs
  tests/it/compute/temporal.rs
Labels: enhancement

#417 Added support to add an interval to a timestamp
  src/array/display.rs
  src/compute/arithmetics/mod.rs
  src/compute/arithmetics/time.rs
  src/compute/cast/primitive_to.rs
  src/compute/temporal.rs
  src/temporal_conversions.rs
  tests/it/temporal_conversions.rs
Labels: feature

#419 Added reading of parquet required dictionary-encoded binary.
  src/io/parquet/read/binary/basic.rs
  tests/it/io/parquet/read.rs
Labels: enhancement

#413 Add `extend`/`extend_unchecked` for `MutableUtf8Array`
  src/array/utf8/mutable.rs
  tests/it/array/utf8/mutable.rs
Labels: enhancement

#422 Bumped parquet2
  Cargo.toml
Labels: backwards-incompatible

#429 Reduced number of combinations in feature tests.
  Cargo.toml
Labels: testing

#426 Improved performance of utf8 validation of large strings via `simdutf8` (-40%)
  Cargo.toml
  benches/read_parquet.rs
  parquet_integration/write_parquet.py
  src/array/ord.rs
  src/array/specification.rs
  src/compute/cast/mod.rs
  src/compute/like.rs
  src/error.rs
  src/ffi/schema.rs
  src/io/avro/read/deserialize.rs
  src/io/avro/read/util.rs
  src/io/csv/read/deserialize.rs
  src/io/parquet/read/schema/metadata.rs
  src/io/parquet/read/statistics/binary.rs
Labels: enhancement

#430 Improved documentation
  src/array/mod.rs
  src/array/primitive/from_natural.rs
  src/array/primitive/mod.rs
  src/datatypes/mod.rs
  src/datatypes/physical_type.rs
  src/types/mod.rs
Labels: documentation

#427 Improved performance of iterator of `Utf8Array` and `BinaryArray` (3-4x)
  Cargo.toml
  benches/iter_utf8.rs
  src/array/binary/mod.rs
  src/array/specification.rs
  src/array/utf8/mod.rs
  src/array/utf8/mutable.rs
Labels: enhancement

#420 Changed IPC `FileWriter` to own the `writer`.
  benches/write_ipc.rs
  examples/extension.rs
  examples/ipc_file_write.rs
  integration-testing/src/bin/arrow-json-integration-test.rs
  integration-testing/src/bin/arrow-stream-to-file.rs
  src/io/ipc/write/writer.rs
  tests/it/io/ipc/write/file.rs
Labels: backwards-incompatible

#434 Improved performance of `PrimitiveGrowable` for nulls (-10%)
  src/array/growable/binary.rs
  src/array/growable/boolean.rs
  src/array/growable/dictionary.rs
  src/array/growable/fixed_binary.rs
  src/array/growable/list.rs
  src/array/growable/mod.rs
  src/array/growable/null.rs
  src/array/growable/primitive.rs
  src/array/growable/structure.rs
  src/array/growable/utf8.rs
  src/array/growable/utils.rs
Labels: enhancement

#438 Fixed panic in division using nulls.
  src/compute/arithmetics/basic/div.rs
Labels: bug

#436 Added example showing parallel writes to parquet (x num_cores)
  examples/parquet_write_parallel/.gitignore
  examples/parquet_write_parallel/Cargo.toml
  examples/parquet_write_parallel/src/main.rs
  guide/src/io/parquet_write.md
Labels: documentation

#431 Changed validity from `&Option<Bitmap>` to `Option<&Bitmap>`.
  guide/src/high_level.md
  src/array/binary/mod.rs
  src/array/binary/mutable.rs
  src/array/boolean/mod.rs
  src/array/boolean/mutable.rs
  src/array/dictionary/mod.rs
  src/array/dictionary/mutable.rs
  src/array/fixed_size_binary/mod.rs
  src/array/fixed_size_binary/mutable.rs
  src/array/fixed_size_list/mod.rs
  src/array/fixed_size_list/mutable.rs
  src/array/list/mod.rs
  src/array/list/mutable.rs
  src/array/mod.rs
  src/array/null.rs
  src/array/primitive/mod.rs
  src/array/primitive/mutable.rs
  src/array/struct_.rs
  src/array/union/mod.rs
  src/array/utf8/mod.rs
  src/array/utf8/mutable.rs
  src/compute/aggregate/memory.rs
  src/compute/arity.rs
  src/compute/boolean.rs
  src/compute/cast/binary_to.rs
  src/compute/cast/boolean_to.rs
  src/compute/cast/mod.rs
  src/compute/cast/primitive_to.rs
  src/compute/cast/utf8_to.rs
  src/compute/comparison/binary.rs
  src/compute/comparison/boolean.rs
  src/compute/comparison/primitive.rs
  src/compute/comparison/utf8.rs
  src/compute/hash.rs
  src/compute/length.rs
  src/compute/like.rs
  src/compute/nullif.rs
  src/compute/sort/common.rs
  src/compute/substring.rs
  src/compute/take/boolean.rs
  src/compute/take/generic_binary.rs
  src/compute/take/primitive.rs
  src/compute/take/structure.rs
  src/compute/utils.rs
  src/io/ipc/write/serialize.rs
  src/io/parquet/write/binary/basic.rs
  src/io/parquet/write/dictionary.rs
  src/io/parquet/write/levels.rs
  src/io/parquet/write/mod.rs
  src/io/parquet/write/utils.rs
  tests/it/array/binary/mod.rs
  tests/it/array/binary/mutable.rs
  tests/it/array/boolean/mod.rs
  tests/it/array/boolean/mutable.rs
  tests/it/array/fixed_size_binary/mutable.rs
  tests/it/array/growable/utils.rs
  tests/it/array/primitive/mod.rs
  tests/it/array/primitive/mutable.rs
  tests/it/array/utf8/mod.rs
  tests/it/array/utf8/mutable.rs
Labels: backwards-incompatible

#452 Simplified CI
  .github/workflows/test.yml
Labels: testing

#450 Added `MutableArray::as_box`
  src/array/binary/mutable.rs
  src/array/boolean/mutable.rs
  src/array/dictionary/mutable.rs
  src/array/fixed_size_binary/mutable.rs
  src/array/fixed_size_list/mutable.rs
  src/array/list/mutable.rs
  src/array/mod.rs
  src/array/primitive/mutable.rs
  src/array/utf8/mutable.rs
Labels: enhancement

#385 Replaced own allocator by `std::Vec`.
  .github/workflows/test.yml
  Cargo.toml
  arrow-pyarrow-integration-testing/src/lib.rs
  arrow-pyarrow-integration-testing/tests/test_sql.py
  benches/arithmetic_kernels.rs
  src/alloc/mod.rs
  src/bitmap/bitmap_ops.rs
  src/buffer/bytes.rs
  src/buffer/immutable.rs
  src/buffer/mod.rs
  src/buffer/mutable.rs
  src/buffer/util.rs
  src/lib.rs
  src/types/bit_chunk.rs
  src/types/mod.rs
  src/vec.rs
  tests/it/alloc.rs
  tests/it/array/utf8/mutable.rs
  tests/it/bitmap/mutable.rs
  tests/it/buffer/immutable.rs
  tests/it/buffer/mutable.rs
  tests/it/main.rs
Labels: feature

#454 cargo fmt
  benches/hash_kernel.rs
  src/io/parquet/read/schema/metadata.rs
Labels: no-changelog

#442 Optimized `null_count`
  benches/bitmap_ops.rs
  src/bitmap/immutable.rs
Labels: enhancement

#432 Allowed accessing validity without importing `Array`
  src/array/binary/mod.rs
  src/array/boolean/mod.rs
  src/array/dictionary/mod.rs
  src/array/fixed_size_binary/mod.rs
  src/array/fixed_size_list/mod.rs
  src/array/list/mod.rs
  src/array/primitive/mod.rs
  src/array/struct_.rs
  src/array/utf8/mod.rs
  src/compute/utils.rs
Labels: enhancement

#456 Minor cleanup of internals.
  src/array/fixed_size_binary/mod.rs
  src/array/fixed_size_list/mod.rs
  src/array/list/mod.rs
  src/array/mod.rs
Labels: no-changelog

#455 Added fmt to CI.
  .github/workflows/test.yml
Labels: testing

#433 Extract parts of datetime
  src/compute/temporal.rs
  tests/it/compute/temporal.rs
Labels: feature

#458 Made importing from FFI `unsafe`
  arrow-pyarrow-integration-testing/src/lib.rs
  examples/ffi.rs
  src/array/binary/ffi.rs
  src/array/boolean/ffi.rs
  src/array/dictionary/ffi.rs
  src/array/ffi.rs
  src/array/list/ffi.rs
  src/array/primitive/ffi.rs
  src/array/struct_.rs
  src/array/union/ffi.rs
  src/array/utf8/ffi.rs
  src/ffi/array.rs
  src/ffi/mod.rs
  src/ffi/schema.rs
  src/lib.rs
  tests/it/ffi.rs
Labels: bug

#460 Added property testing
  Cargo.toml
  tests/it/array/binary/mutable.rs
  tests/it/array/utf8/mutable.rs
  tests/it/bitmap/bitmap_ops.rs
  tests/it/bitmap/mod.rs
  tests/it/bitmap/utils/mod.rs
  tests/it/bitmap/utils/slice_iterator.rs
Labels: testing

#445 Improved performance of sum aggregation via aligned loads (-10%)
  src/compute/aggregate/sum.rs
  src/types/simd/mod.rs
  src/types/simd/native.rs
  src/types/simd/packed.rs
Labels: enhancement

#461 Un-nested `compute::arithemtics::basic`
  benches/arithmetic_kernels.rs
  src/compute/arithmetics/basic/add.rs
  src/compute/arithmetics/basic/div.rs
  src/compute/arithmetics/basic/mod.rs
  src/compute/arithmetics/basic/mul.rs
  src/compute/arithmetics/basic/pow.rs
  src/compute/arithmetics/basic/rem.rs
  src/compute/arithmetics/basic/sub.rs
  src/compute/arithmetics/mod.rs
  tests/it/compute/aggregate/sum.rs
  tests/it/compute/arithmetics/basic/add.rs
  tests/it/compute/arithmetics/basic/div.rs
  tests/it/compute/arithmetics/basic/mul.rs
  tests/it/compute/arithmetics/basic/pow.rs
  tests/it/compute/arithmetics/basic/rem.rs
  tests/it/compute/arithmetics/basic/sub.rs
Labels: backwards-incompatible

#462 Improved documentation
  src/array/growable/list.rs
  src/array/mod.rs
  src/bitmap/mod.rs
  src/buffer/mod.rs
  src/compute/comparison/mod.rs
  src/compute/mod.rs
  src/datatypes/mod.rs
  src/doc/lib.md
  src/ffi/mod.rs
  src/io/mod.rs
  src/io/parquet/write/mod.rs
  src/io/parquet/write/stream.rs
  src/lib.rs
  src/record_batch.rs
  src/scalar/mod.rs
  src/types/mod.rs
Labels: documentation

#468 Added `MutableBitmap::shrink_to_fit`
  src/bitmap/mutable.rs
  tests/it/bitmap/mutable.rs
Labels: enhancement

#471 Made writing stream to parquet require a non-static lifetime
  src/io/parquet/write/stream.rs
Labels: bug

#470 Added `GrowableFixedSizeList` and improved `MutableFixedSizeListArray`
  src/array/fixed_size_list/mutable.rs
  src/array/growable/fixed_size_list.rs
  src/array/growable/mod.rs
  tests/it/array/equal/fixed_size_list.rs
  tests/it/array/fixed_size_list/mutable.rs
  tests/it/array/growable/fixed_size_list.rs
  tests/it/array/growable/mod.rs
Labels: enhancement

#476 Added more documentation
  src/array/list/mod.rs
  src/array/list/mutable.rs
  src/array/mod.rs
  src/array/union/mod.rs
  src/datatypes/mod.rs
  src/ffi/ffi.rs
  src/ffi/mod.rs
  src/io/avro/mod.rs
  src/io/avro/read/mod.rs
  src/io/csv/mod.rs
  src/io/csv/read/deserialize.rs
  src/io/csv/read/mod.rs
  src/io/csv/read/reader.rs
  src/io/csv/write/mod.rs
  src/io/csv/write/serialize.rs
  src/io/json/mod.rs
  src/io/json/read/reader.rs
  src/io/parquet/read/mod.rs
  src/io/parquet/read/record_batch.rs
  src/io/parquet/read/schema/mod.rs
  src/io/parquet/read/statistics/mod.rs
  src/io/parquet/write/mod.rs
  src/io/parquet/write/record_batch.rs
  src/io/parquet/write/schema.rs
  src/io/parquet/write/stream.rs
Labels: documentation

#474 DRY of type check and len check code in `compute`
  src/compute/arithmetics/basic/add.rs
  src/compute/arithmetics/basic/common.rs
  src/compute/arithmetics/basic/div.rs
  src/compute/arithmetics/basic/mod.rs
  src/compute/arithmetics/basic/mul.rs
  src/compute/arithmetics/basic/rem.rs
  src/compute/arithmetics/basic/sub.rs
  src/compute/arithmetics/decimal/add.rs
  src/compute/arithmetics/decimal/div.rs
  src/compute/arithmetics/decimal/mul.rs
  src/compute/arithmetics/decimal/sub.rs
  src/compute/arity.rs
  src/compute/nullif.rs
Labels: testing
