Repository jorgecarleitao/arrow2, pull requests merged in 2022-04, with the labels that each got.

#931 Fixed guide deployment
  .github/workflows/docs.yml
Labels: documentation

#939 Simpler IPC code
  src/io/ipc/write/common.rs
  src/io/ipc/write/mod.rs
  src/io/ipc/write/serialize.rs
Labels: enhancement

#942 Added test for MapArray
  tests/it/array/map/mod.rs
  tests/it/array/mod.rs
Labels: testing

#945 Fixed bug in reading binary parquet
  src/io/parquet/read/deserialize/binary/basic.rs
Labels: bug

#947 Made GroupFilter `Send + Sync`
  src/io/parquet/read/file.rs
Labels: backwards-incompatible

#923 Migrate to latest parquet2
  Cargo.toml
  arrow-parquet-integration-testing/src/main.rs
  benches/write_parquet.rs
  examples/parquet_write.rs
  examples/parquet_write_parallel/src/main.rs
  src/array/fixed_size_binary/mod.rs
  src/doc/lib.md
  src/error.rs
  src/io/parquet/mod.rs
  src/io/parquet/read/deserialize/binary/basic.rs
  src/io/parquet/read/deserialize/binary/nested.rs
  src/io/parquet/read/deserialize/binary/utils.rs
  src/io/parquet/read/deserialize/boolean/basic.rs
  src/io/parquet/read/deserialize/boolean/nested.rs
  src/io/parquet/read/deserialize/dictionary.rs
  src/io/parquet/read/deserialize/fixed_size_binary/basic.rs
  src/io/parquet/read/deserialize/mod.rs
  src/io/parquet/read/deserialize/nested_utils.rs
  src/io/parquet/read/deserialize/primitive/basic.rs
  src/io/parquet/read/deserialize/primitive/nested.rs
  src/io/parquet/read/deserialize/simple.rs
  src/io/parquet/read/deserialize/utils.rs
  src/io/parquet/read/indexes/binary.rs
  src/io/parquet/read/indexes/boolean.rs
  src/io/parquet/read/indexes/fixed_len_binary.rs
  src/io/parquet/read/indexes/mod.rs
  src/io/parquet/read/indexes/primitive.rs
  src/io/parquet/read/mod.rs
  src/io/parquet/read/row_group.rs
  src/io/parquet/read/schema/convert.rs
  src/io/parquet/read/schema/mod.rs
  src/io/parquet/read/statistics/primitive.rs
  src/io/parquet/write/binary/basic.rs
  src/io/parquet/write/binary/mod.rs
  src/io/parquet/write/binary/nested.rs
  src/io/parquet/write/boolean/basic.rs
  src/io/parquet/write/boolean/nested.rs
  src/io/parquet/write/dictionary.rs
  src/io/parquet/write/file.rs
  src/io/parquet/write/fixed_len_bytes.rs
  src/io/parquet/write/mod.rs
  src/io/parquet/write/primitive/basic.rs
  src/io/parquet/write/primitive/mod.rs
  src/io/parquet/write/primitive/nested.rs
  src/io/parquet/write/row_group.rs
  src/io/parquet/write/schema.rs
  src/io/parquet/write/sink.rs
  src/io/parquet/write/utf8/basic.rs
  src/io/parquet/write/utf8/mod.rs
  src/io/parquet/write/utf8/nested.rs
  src/io/parquet/write/utils.rs
  tests/it/io/parquet/mod.rs
  tests/it/io/parquet/read_indexes.rs
  tests/it/io/parquet/write.rs
  tests/it/io/parquet/write_async.rs
Labels: feature

#941 Fixed error in writing fixedSizeListArray to parquet
  src/io/parquet/read/deserialize/binary/basic.rs
  src/io/parquet/read/deserialize/fixed_size_binary/basic.rs
  src/io/parquet/read/deserialize/mod.rs
  src/io/parquet/read/deserialize/utils.rs
  src/io/parquet/write/mod.rs
Labels: bug

#960 Fixed patch of integration tests
  integration-testing/unskip.patch
Labels: testing

#961 Added support for non-ordered projections to IPC reading
  src/io/ipc/read/common.rs
  src/io/ipc/read/file_async.rs
  src/io/ipc/read/reader.rs
  tests/it/io/ipc/read/file.rs
Labels: feature

#964 Reduced memory usage in reading parquet
  examples/parquet_read.rs
  src/io/parquet/read/deserialize/utils.rs
Labels: enhancement

#965 Fixed bug in writing csv with buffer resizing
  src/io/csv/write/serialize.rs
  tests/it/io/csv/write.rs
Labels: bug

#968 Fixed writing required list to parquet
  src/io/parquet/write/levels.rs
  tests/it/io/parquet/mod.rs
  tests/it/io/parquet/read.rs
  tests/it/io/parquet/write.rs
Labels: bug

#969 Fixed API bug in `async` read of IPC metadata
  src/io/ipc/read/file_async.rs
  src/io/ipc/read/reader.rs
Labels: bug

#971 Made reading of IPC dictionaries lazy
  src/io/flight/mod.rs
  src/io/ipc/read/file_async.rs
  src/io/ipc/read/reader.rs
Labels: enhancement

#970 Allowed creating IPC `FileWriter` without writing to the file
  .github/workflows/test.yml
  examples/extension.rs
  examples/ipc_file_write.rs
  src/io/ipc/write/writer.rs
Labels: enhancement

#972 Added support to append to existing IPC Arrow file
  src/io/flight/mod.rs
  src/io/ipc/append/mod.rs
  src/io/ipc/mod.rs
  src/io/ipc/read/mod.rs
  src/io/ipc/read/reader.rs
  src/io/ipc/write/common.rs
  src/io/ipc/write/file_async.rs
  src/io/ipc/write/mod.rs
  src/io/ipc/write/stream.rs
  src/io/ipc/write/stream_async.rs
  src/io/ipc/write/writer.rs
  tests/it/io/ipc/write/file.rs
  tests/it/io/ipc/write/file_append.rs
  tests/it/io/ipc/write/mod.rs
Labels: feature
