Repository jorgecarleitao/arrow2, pull requests merged in 2022-03, with the labels that each got.

#873 Added `try_new` and `new` to all arrays
  src/array/README.md
  src/array/binary/mod.rs
  src/array/boolean/mod.rs
  src/array/fixed_size_binary/mod.rs
  src/array/fixed_size_list/mod.rs
  src/array/list/mod.rs
  src/array/map/mod.rs
  src/array/null.rs
  src/array/primitive/mod.rs
  src/array/specification.rs
  src/array/struct_/mod.rs
  src/array/union/mod.rs
  src/array/utf8/mod.rs
  tests/it/array/list/mod.rs
Labels: enhancement

#877 implemented `futures::Sink` for parquet async writer
  src/io/parquet/write/mod.rs
  src/io/parquet/write/sink.rs
  src/io/parquet/write/stream.rs
  tests/it/io/parquet/mod.rs
  tests/it/io/parquet/write_async.rs
Labels: enhancement

#882 Fixed unsoundness of `#derive(Clone)` for FFI structs
  src/ffi/generated.rs
Labels: bug

#881 Re-added support for reading nested parquet arrays
  src/io/parquet/read/deserialize/mod.rs
  src/io/parquet/read/deserialize/nested_utils.rs
  tests/it/io/parquet/mod.rs
  tests/it/io/parquet/read.rs
Labels: enhancement, no-changelog

#883 Simplified code to generate parquet files for tests
  parquet_integration/write_parquet.py
  tests/it/io/parquet/mod.rs
  tests/it/io/parquet/read.rs
  tests/it/io/parquet/write.rs
Labels: testing

#884 Fix edge case in reading nested parquet
  parquet_integration/write_parquet.py
  src/io/parquet/read/deserialize/nested_utils.rs
  tests/it/io/parquet/mod.rs
  tests/it/io/parquet/read.rs
Labels: bug

#885 Fixed integration test
  integration-testing/src/flight_client_scenarios/integration_test.rs
Labels: bug

#886 Added `MutableFixedList::mut_values`
  src/array/fixed_size_list/mutable.rs
Labels: enhancement

#849 Support to read/write from/to ODBC
  .github/workflows/integration-odbc.yml
  Cargo.toml
  README.md
  arrow-odbc-integration-testing/Cargo.toml
  arrow-odbc-integration-testing/docker-compose.yml
  arrow-odbc-integration-testing/src/lib.rs
  arrow-odbc-integration-testing/src/read.rs
  arrow-odbc-integration-testing/src/write.rs
  examples/io_odbc.rs
  guide/src/io/README.md
  guide/src/io/odbc.md
  src/io/mod.rs
  src/io/odbc/mod.rs
  src/io/odbc/read/deserialize.rs
  src/io/odbc/read/mod.rs
  src/io/odbc/read/schema.rs
  src/io/odbc/write/mod.rs
  src/io/odbc/write/schema.rs
  src/io/odbc/write/serialize.rs
Labels: feature

#888 Added support for datetime reads from ODBC
  arrow-odbc-integration-testing/src/read.rs
  src/io/odbc/read/deserialize.rs
  src/io/odbc/read/mod.rs
Labels: enhancement

#891 Bug fix in offset for sliced unions
  src/array/union/mod.rs
  tests/it/array/union.rs
Labels: bug

#892 Added back reading nested dictionary parquet pages
  src/io/parquet/read/deserialize/primitive/basic.rs
  src/io/parquet/read/deserialize/primitive/nested.rs
  tests/it/io/parquet/read.rs
Labels: no-changelog

#894 Fixed error in computing `min_max` in `std::simd`
  src/compute/aggregate/simd/packed.rs
  tests/it/compute/aggregate/min_max.rs
Labels: bug, no-changelog

#897 Added support for min/max for decimal
  src/compute/aggregate/min_max.rs
  src/compute/aggregate/simd/mod.rs
  src/compute/aggregate/simd/native.rs
  tests/it/compute/aggregate/min_max.rs
Labels: enhancement

#899 Added support for `hash` of `month_day_ns` arrays
  src/compute/hash.rs
Labels: feature

#898 Use more idiomatic versions
  src/buffer/immutable.rs
  src/compute/arithmetics/decimal/add.rs
  src/compute/arithmetics/decimal/div.rs
  src/compute/arithmetics/decimal/mul.rs
  src/compute/arithmetics/decimal/sub.rs
  src/compute/arity.rs
  src/compute/cast/binary_to.rs
  src/compute/cast/boolean_to.rs
  src/compute/hash.rs
  src/compute/length.rs
  src/compute/take/generic_binary.rs
  src/io/parquet/write/mod.rs
Labels: enhancement

#900 Added cast to `months_days_ns`
  src/compute/cast/mod.rs
  src/compute/cast/primitive_to.rs
  tests/it/compute/cast.rs
Labels: feature

#901 Simpler code (DRY)
  src/scalar/equal.rs
Labels: testing

#902 Added `GrowableUnion`
  src/array/growable/mod.rs
  src/array/growable/union.rs
  src/array/union/mod.rs
  tests/it/array/growable/mod.rs
  tests/it/array/growable/union.rs
  tests/it/array/union.rs
Labels: feature

#904 Fixed edge case in reading multiple parquet pages
  src/io/parquet/read/deserialize/mod.rs
  src/io/parquet/read/deserialize/nested_utils.rs
Labels: bug

#906 Removed `println`
  src/io/odbc/read/deserialize.rs
Labels: no-changelog

#907 Support `sum`, `min` and `max` for extension and decimal
  src/compute/aggregate/min_max.rs
  src/compute/aggregate/simd/mod.rs
  src/compute/aggregate/simd/native.rs
  src/compute/aggregate/sum.rs
Labels: enhancement

#908 Added support to write `ListArray` to Avro
  src/io/avro/write/schema.rs
  src/io/avro/write/serialize.rs
  tests/it/io/avro/write.rs
Labels: feature

#909 Added support to write `StructArray` to Avro
  src/io/avro/read/nested.rs
  src/io/avro/read/schema.rs
  src/io/avro/write/schema.rs
  src/io/avro/write/serialize.rs
  tests/it/io/avro/read.rs
  tests/it/io/avro/write.rs
Labels: feature

#910 Added more tests
  src/array/primitive/mutable.rs
  src/array/utf8/mod.rs
  tests/it/array/fixed_size_binary/mod.rs
  tests/it/array/primitive/fmt.rs
  tests/it/array/primitive/mod.rs
  tests/it/array/primitive/mutable.rs
  tests/it/array/utf8/mod.rs
Labels: testing

#914 Fixed error in `FixedSizeBinaryArray::new_null`
  src/array/fixed_size_binary/mod.rs
  tests/it/array/fixed_size_binary/mod.rs
Labels: bug

#919 Typo fix
  README.md
Labels: documentation

#924 Fixed support to read dict nested binary parquet
  src/io/parquet/read/deserialize/binary/basic.rs
  src/io/parquet/read/deserialize/binary/nested.rs
  tests/it/io/parquet/read.rs
Labels: bug

#927 Removed un-needed generic parameter
  src/io/parquet/read/deserialize/primitive/basic.rs
  src/io/parquet/read/deserialize/primitive/nested.rs
Labels: enhancement
