Repository jorgecarleitao/arrow2, pull requests merged in 2022-06, with the labels that each got.

#1035 Bumped parquet2
  Cargo.toml
  arrow-parquet-integration-testing/src/main.rs
  benches/write_parquet.rs
  examples/parquet_write.rs
  examples/parquet_write_parallel/src/main.rs
  src/doc/lib.md
  src/io/parquet/write/file.rs
  src/io/parquet/write/sink.rs
  tests/it/io/parquet/mod.rs
  tests/it/io/parquet/read_indexes.rs
  tests/it/io/parquet/write.rs
Labels: backwards-incompatible

#1038 Improved lifetime in writing parquet
  examples/parquet_write_parallel/src/main.rs
  src/io/parquet/write/pages.rs
Labels: no-changelog

#1044 Fixed error in reading some required fields in nested parquet
  src/io/parquet/read/deserialize/binary/basic.rs
  src/io/parquet/read/deserialize/binary/nested.rs
  src/io/parquet/read/deserialize/boolean/basic.rs
  src/io/parquet/read/deserialize/boolean/nested.rs
Labels: bug, no-changelog

#1047 Cleaned docs for BinaryArray
  src/array/binary/from.rs
  src/array/binary/iterator.rs
  src/array/binary/mod.rs
  src/array/equal/binary.rs
  src/array/utf8/mod.rs
Labels: documentation

#1024 Improved performance of deserializing JSON (2x)
  Cargo.toml
  benches/read_json.rs
  examples/json_read.rs
  src/io/avro/read/decompress.rs
  src/io/avro/write/compress.rs
  src/io/json/mod.rs
  src/io/json/read/deserialize.rs
  src/io/json/read/infer_schema.rs
  src/io/json/read/mod.rs
  src/io/json/write/mod.rs
  src/io/json/write/serialize.rs
  src/io/json/write/utf8.rs
  src/io/json_integration/mod.rs
  src/io/ndjson/read/deserialize.rs
  src/io/ndjson/read/file.rs
  tests/it/io/json/read.rs
  tests/it/io/ndjson/read.rs
Labels: backwards-incompatible

#1046 Fixed using lower limit than size of first parquet row group
  src/io/parquet/read/file.rs
  src/io/parquet/read/row_group.rs
Labels: bug

#1054 Improve Docs Readability
  DEVELOPMENT.md
  README.md
  guide/src/io/csv_reader.md
  guide/src/io/parquet_read.md
  src/array/README.md
Labels: documentation

#1057 Fixed missing validation of number of encodings passed when writing to parquet
  src/io/parquet/write/row_group.rs
  src/io/parquet/write/sink.rs
Labels: bug

#1062 Fixed divide by zero on reading empty row group
  src/io/parquet/read/deserialize/null.rs
Labels: bug

#1065 Added missing link to guide
  guide/src/SUMMARY.md
Labels: documentation

#1064 Added more tests
  tests/it/compute/comparison.rs
Labels: testing

#1066 Added cast to/from `Null` from/to every type
  src/compute/cast/mod.rs
Labels: enhancement

#1063 Added support to write parquet `_metadata` sidecar
  src/io/parquet/write/file.rs
  src/io/parquet/write/mod.rs
Labels: feature

#1061 Added cow APIs (2x-10x vs non-cow)
  Cargo.toml
  benches/assign_ops.rs
  benches/bitmap_assign_ops.rs
  src/array/boolean/mod.rs
  src/array/primitive/mod.rs
  src/bitmap/assign_ops.rs
  src/bitmap/immutable.rs
  src/bitmap/mod.rs
  src/bitmap/mutable.rs
  src/bitmap/utils/chunks_exact_mut.rs
  src/bitmap/utils/mod.rs
  src/buffer/immutable.rs
  src/types/bit_chunk.rs
  tests/it/array/boolean/mod.rs
  tests/it/array/primitive/mod.rs
  tests/it/bitmap/assign_ops.rs
  tests/it/bitmap/mod.rs
Labels: feature

#1067 Improved performance in lexical write (~5%)
  src/util/lexical.rs
Labels: enhancement

#1068 Updated patch to arrow integration tests
  integration-testing/unskip.patch
Labels: testing

#1055 Made `chunk_size` optional in parquet's `column_iter_to_arrays`
  src/io/parquet/read/deserialize/binary/basic.rs
  src/io/parquet/read/deserialize/binary/dictionary.rs
  src/io/parquet/read/deserialize/binary/mod.rs
  src/io/parquet/read/deserialize/binary/nested.rs
  src/io/parquet/read/deserialize/boolean/basic.rs
  src/io/parquet/read/deserialize/boolean/mod.rs
  src/io/parquet/read/deserialize/boolean/nested.rs
  src/io/parquet/read/deserialize/dictionary.rs
  src/io/parquet/read/deserialize/fixed_size_binary/basic.rs
  src/io/parquet/read/deserialize/fixed_size_binary/dictionary.rs
  src/io/parquet/read/deserialize/mod.rs
  src/io/parquet/read/deserialize/nested_utils.rs
  src/io/parquet/read/deserialize/null.rs
  src/io/parquet/read/deserialize/primitive/basic.rs
  src/io/parquet/read/deserialize/primitive/dictionary.rs
  src/io/parquet/read/deserialize/primitive/mod.rs
  src/io/parquet/read/deserialize/primitive/nested.rs
  src/io/parquet/read/deserialize/simple.rs
  src/io/parquet/read/deserialize/utils.rs
  src/io/parquet/read/mod.rs
  src/io/parquet/read/row_group.rs
  tests/it/io/parquet/read_indexes.rs
Labels: backwards-incompatible

#1051 Added support to read and write f16
  README.md
  src/array/mod.rs
  src/array/primitive/mod.rs
  src/compute/arithmetics/mod.rs
  src/compute/cast/mod.rs
  src/compute/cast/primitive_to.rs
  src/compute/comparison/mod.rs
  src/compute/comparison/simd/native.rs
  src/compute/comparison/simd/packed.rs
  src/datatypes/mod.rs
  src/io/json_integration/read/array.rs
  src/types/mod.rs
  src/types/native.rs
  src/types/simd/mod.rs
  src/types/simd/native.rs
  tests/it/compute/cast.rs
  tests/it/compute/comparison.rs
Labels: feature

#1069 Removed leftovers of a merge conflict in example
  examples/parquet_write_parallel/src/main.rs
Labels: documentation, no-changelog

#1070 Added `compute::arity_assign`
  benches/assign_ops.rs
  src/compute/arity_assign.rs
  src/compute/mod.rs
  tests/it/compute/arity_assign.rs
  tests/it/compute/mod.rs
Labels: enhancement

#1071 Bumped parquet2 (minor) requirement
  Cargo.toml
Labels: bug

#1078 Fixed panic in bitmap assign_mut
  src/bitmap/immutable.rs
  tests/it/bitmap/assign_ops.rs
Labels: bug

#1079 Improved performance of `Bitmap::make_mut` with offset
  src/bitmap/immutable.rs
Labels: enhancement

#1081 Fixed error in chunked_mut bitmap
  src/bitmap/utils/chunk_iterator/chunks_exact.rs
  src/bitmap/utils/chunks_exact_mut.rs
  src/compute/arity_assign.rs
  tests/it/bitmap/assign_ops.rs
  tests/it/bitmap/utils/bit_chunks_exact.rs
Labels: bug

#1075 Panic-free read of IPC files
  Cargo.toml
  README.md
  integration-testing/Cargo.toml
  integration-testing/src/flight_client_scenarios/integration_test.rs
  integration-testing/src/flight_server_scenarios/integration_test.rs
  src/array/fixed_size_binary/mod.rs
  src/array/fixed_size_list/mod.rs
  src/io/flight/mod.rs
  src/io/ipc/mod.rs
  src/io/ipc/read/array/binary.rs
  src/io/ipc/read/array/boolean.rs
  src/io/ipc/read/array/fixed_size_binary.rs
  src/io/ipc/read/array/list.rs
  src/io/ipc/read/array/map.rs
  src/io/ipc/read/array/null.rs
  src/io/ipc/read/array/primitive.rs
  src/io/ipc/read/array/union.rs
  src/io/ipc/read/array/utf8.rs
  src/io/ipc/read/common.rs
  src/io/ipc/read/error.rs
  src/io/ipc/read/file_async.rs
  src/io/ipc/read/mod.rs
  src/io/ipc/read/read_basic.rs
  src/io/ipc/read/reader.rs
  src/io/ipc/read/schema.rs
  src/io/ipc/read/stream.rs
  src/io/ipc/read/stream_async.rs
  tests/it/io/ipc/read/file.rs
Labels: bug

#1083 Improved docs for `BooleanArray`
  src/array/boolean/from.rs
  src/array/boolean/iterator.rs
  src/array/boolean/mod.rs
  src/array/primitive/mod.rs
Labels: documentation

#1082 Made IPC projection not sort projection
  src/io/ipc/read/common.rs
  src/io/ipc/read/file_async.rs
  src/io/ipc/read/reader.rs
  tests/it/io/ipc/read/file.rs
Labels: bug

#1084 Replaced some macros by generics
  src/compute/arithmetics/mod.rs
Labels: enhancement

#1086 Fixed panic when reading FixedSizeBinary from IPC
  src/io/ipc/read/array/fixed_size_binary.rs
Labels: bug, no-changelog

#1085 Removed un-necessary allocation in `assign_ops`
  benches/assign_ops.rs
  examples/cow.rs
  src/array/boolean/mod.rs
  src/array/primitive/mod.rs
  src/array/primitive/mutable.rs
  src/buffer/immutable.rs
  src/compute/arity_assign.rs
  tests/it/array/boolean/mod.rs
  tests/it/array/primitive/mod.rs
Labels: enhancement

#1087 Renamed `Bitmap::null_count` to `Bitmap::unset_bits`
  benches/bitmap_ops.rs
  benches/slices_iterator.rs
  src/array/binary/mutable.rs
  src/array/boolean/mutable.rs
  src/array/mod.rs
  src/array/physical_binary.rs
  src/array/primitive/mutable.rs
  src/array/utf8/mutable.rs
  src/bitmap/assign_ops.rs
  src/bitmap/bitmap_ops.rs
  src/bitmap/immutable.rs
  src/bitmap/mutable.rs
  src/bitmap/utils/slice_iterator.rs
  src/compute/aggregate/min_max.rs
  src/compute/boolean.rs
  src/compute/filter.rs
  src/compute/sort/common.rs
  src/compute/sort/primitive/sort.rs
  src/io/parquet/write/binary/basic.rs
  src/io/parquet/write/boolean/basic.rs
  src/io/parquet/write/dictionary.rs
  tests/it/array/primitive/mutable.rs
  tests/it/bitmap/mod.rs
  tests/it/bitmap/mutable.rs
  tests/it/bitmap/utils/mod.rs
  tests/it/bitmap/utils/slice_iterator.rs
Labels: backwards-incompatible

#1090 Accept decoding parquet's `i64` into `u32` written by `pyarrow`
  src/io/parquet/read/deserialize/mod.rs
  src/io/parquet/read/deserialize/simple.rs
  src/io/parquet/read/statistics/mod.rs
  tests/it/io/parquet/read.rs
Labels: enhancement

#1093 Raise error when invalid fields are passed to flight
  integration-testing/src/flight_client_scenarios/integration_test.rs
  integration-testing/src/flight_server_scenarios/integration_test.rs
  src/io/flight/mod.rs
Labels: bug

#1088 Simplified code
  src/array/primitive/mod.rs
  src/array/specification.rs
  src/array/utf8/mod.rs
  src/array/utf8/mutable.rs
Labels: enhancement

#1096 Added notes about creating parquet files and submodules in the development documentation
  DEVELOPMENT.md
Labels: documentation

#1094 Exposed utilities in `io::flight`
  .github/workflows/test.yml
  src/io/flight/mod.rs
  tests/it/io/flight/mod.rs
  tests/it/io/mod.rs
Labels: enhancement

#1097 Added support for projections in reading IPC streams
  integration-testing/src/bin/arrow-stream-to-file.rs
  src/io/ipc/read/stream.rs
  tests/it/io/ipc/common.rs
  tests/it/io/ipc/read/stream.rs
  tests/it/io/ipc/write/stream.rs
  tests/it/io/ipc/write_file_async.rs
  tests/it/io/ipc/write_stream_async.rs
Labels: feature

#1089 Removed `Buffer::into_mut` and `make_mut` functions
  src/array/utf8/mutable.rs
  src/buffer/bytes.rs
  src/buffer/immutable.rs
  src/compute/arity_assign.rs
Labels: backwards-incompatible

#1099 Simplified `Bytes` (internal)
  src/buffer/bytes.rs
  src/buffer/foreign.rs
  src/buffer/mod.rs
  src/ffi/array.rs
Labels: testing

#1102 Enabled more integration tests with pyarrow
  .github/workflows/integration-parquet.yml
  arrow-parquet-integration-testing/main.py
  arrow-parquet-integration-testing/src/main.rs
  src/io/parquet/write/pages.rs
Labels: testing

#1103 Added more tests
  tests/it/array/utf8/to_mutable.rs
Labels: testing

#1107 Improved internal docs
  src/io/parquet/read/deserialize/README.md
  src/io/parquet/read/deserialize/simple.rs
Labels: documentation

#1100 Reduced need of `unsafe` in FFI
  arrow-pyarrow-integration-testing/src/c_stream.rs
  arrow-pyarrow-integration-testing/src/lib.rs
  examples/ffi.rs
  src/buffer/bytes.rs
  src/ffi/array.rs
  src/ffi/mod.rs
  src/ffi/stream.rs
  tests/it/ffi/data.rs
  tests/it/ffi/stream.rs
Labels: backwards-incompatible

#1104 Avoid clone in `with_validity`
  src/array/binary/mod.rs
  src/array/boolean/mod.rs
  src/array/dictionary/mod.rs
  src/array/fixed_size_binary/mod.rs
  src/array/fixed_size_list/mod.rs
  src/array/list/mod.rs
  src/array/map/mod.rs
  src/array/mod.rs
  src/array/null.rs
  src/array/primitive/mod.rs
  src/array/struct_/mod.rs
  src/array/utf8/mod.rs
  src/compute/comparison/binary.rs
  src/compute/comparison/boolean.rs
  src/compute/comparison/primitive.rs
  src/compute/comparison/utf8.rs
  tests/it/compute/comparison.rs
Labels: backwards-incompatible

#1108 Fixed error in reading chunked parquet
  src/io/parquet/read/deserialize/utils.rs
  src/io/parquet/read/row_group.rs
Labels: bug

#1105 Reduced reallocations when reading from IPC (`~12%`)
  examples/ipc_file_read.rs
  integration-testing/src/flight_client_scenarios/integration_test.rs
  integration-testing/src/flight_server_scenarios/integration_test.rs
  src/io/flight/mod.rs
  src/io/ipc/append/mod.rs
  src/io/ipc/read/array/binary.rs
  src/io/ipc/read/array/dictionary.rs
  src/io/ipc/read/array/fixed_size_binary.rs
  src/io/ipc/read/array/fixed_size_list.rs
  src/io/ipc/read/array/list.rs
  src/io/ipc/read/array/map.rs
  src/io/ipc/read/array/primitive.rs
  src/io/ipc/read/array/struct_.rs
  src/io/ipc/read/array/union.rs
  src/io/ipc/read/array/utf8.rs
  src/io/ipc/read/common.rs
  src/io/ipc/read/deserialize.rs
  src/io/ipc/read/file_async.rs
  src/io/ipc/read/mod.rs
  src/io/ipc/read/read_basic.rs
  src/io/ipc/read/reader.rs
  src/io/ipc/read/stream.rs
  src/io/ipc/read/stream_async.rs
  src/io/mod.rs
  src/io/readbuf.rs
Labels: enhancement

#1109 Improved examples
  examples/avro_read_async.rs
  examples/parquet_read.rs
  examples/parquet_read_parallel/src/main.rs
  examples/parquet_write_async.rs
  examples/parquet_write_parallel/src/main.rs
Labels: documentation

#1106 Removed some panics reading invalid parquet files
  Cargo.toml
  src/io/parquet/read/deserialize/binary/basic.rs
  src/io/parquet/read/deserialize/binary/nested.rs
  src/io/parquet/read/deserialize/boolean/basic.rs
  src/io/parquet/read/deserialize/boolean/nested.rs
  src/io/parquet/read/deserialize/dictionary.rs
  src/io/parquet/read/deserialize/fixed_size_binary/basic.rs
  src/io/parquet/read/deserialize/nested_utils.rs
  src/io/parquet/read/deserialize/primitive/basic.rs
  src/io/parquet/read/deserialize/primitive/nested.rs
  src/io/parquet/read/deserialize/utils.rs
Labels: enhancement

#1111 Added more tests
  src/array/utf8/mod.rs
  tests/it/array/utf8/mod.rs
  tests/it/array/utf8/mutable.rs
Labels: documentation

#1113 Fixed panic in writing dictionaries to parquet
  src/io/parquet/read/deserialize/simple.rs
  src/io/parquet/write/dictionary.rs
  tests/it/array/mod.rs
  tests/it/compute/arithmetics/time.rs
  tests/it/io/parquet/mod.rs
Labels: bug

#1117 Aligned name of `FixedSizeBinaryArray::values_iter`
  src/array/fixed_size_binary/iterator.rs
Labels: bug

#1115 Added test for scalar division
  tests/it/compute/arithmetics/decimal/div.rs
Labels: testing

#1116 Renamed `f16::as_f32` to `f16::to_f32`
  src/compute/cast/primitive_to.rs
  src/types/native.rs
Labels: backwards-incompatible, no-changelog

#1122 Added support to write and read Intervals from and to parquet
  .github/workflows/test.yml
  examples/parquet_write_parallel/src/main.rs
  src/io/parquet/read/deserialize/simple.rs
  src/io/parquet/read/mod.rs
  src/io/parquet/read/statistics/fixlen.rs
  src/io/parquet/read/statistics/mod.rs
  src/io/parquet/write/mod.rs
  tests/it/io/parquet/mod.rs
Labels: feature

#1124 Improved parquet read performance
  src/error.rs
  src/io/parquet/read/row_group.rs
Labels: enhancement

#1128 Removed `O(N)` clone in writing CSV
  src/io/csv/write/mod.rs
  tests/it/io/csv/write.rs
Labels: enhancement

#1127 Avoid zeroed allocation in reading avro
  src/io/avro/read/block.rs
  src/io/avro/read/util.rs
  src/io/avro/read_async/block.rs
  src/io/avro/read_async/metadata.rs
Labels: enhancement

#1130 Cleaned example
  examples/parquet_write_parallel/src/main.rs
Labels: enhancement

#1131 Improved example
  examples/cow.rs
Labels: documentation
