Repository jorgecarleitao/arrow2, pull requests merged in 2022-11, with the labels that each got.

#1293 Fixed error in memory usage of sliced binary/list/utf8arrays
  src/compute/aggregate/memory.rs
Labels: bug

#1290 Fixed link from the API to the guide
  src/doc/lib.md
Labels: documentation

#1284 Improved ZipValidity iterators
  src/array/binary/mod.rs
  src/array/boolean/iterator.rs
  src/array/boolean/mod.rs
  src/array/dictionary/mod.rs
  src/array/fixed_size_binary/iterator.rs
  src/array/fixed_size_list/iterator.rs
  src/array/list/iterator.rs
  src/array/map/iterator.rs
  src/array/primitive/iterator.rs
  src/array/primitive/mod.rs
  src/array/struct_/iterator.rs
  src/array/utf8/mod.rs
  src/bitmap/utils/zip_validity.rs
  src/io/avro/write/serialize.rs
  src/io/json/write/serialize.rs
Labels: enhancement

#1286 Fixed descending ordering when specify nulls first
  src/compute/merge_sort/mod.rs
  tests/it/compute/merge_sort.rs
Labels: bug

#1279 Add avro record names when converting arrow schema to avro
  src/io/avro/write/schema.rs
  tests/it/io/avro/write.rs
Labels: bug

#1300 Added support for Extension types in ffi
  src/ffi/schema.rs
  tests/it/ffi/data.rs
Labels: bug

#1301 Added `reserve` to pushable containers in parquet extend_from_decoder
  src/io/parquet/read/deserialize/binary/utils.rs
  src/io/parquet/read/deserialize/fixed_size_binary/utils.rs
  src/io/parquet/read/deserialize/utils.rs
Labels: enhancement
