Repository jorgecarleitao/arrow2, pull requests merged in 2022-02, with the labels that each got.

#803 Added support for other timestamp units from parquet
  parquet_integration/write_parquet.py
  src/io/parquet/read/mod.rs
  src/io/parquet/read/primitive/basic.rs
  src/io/parquet/read/primitive/mod.rs
  src/io/parquet/read/row_group.rs
  src/io/parquet/read/statistics/binary.rs
  src/io/parquet/read/statistics/mod.rs
  src/io/parquet/read/statistics/primitive.rs
  tests/it/io/parquet/mod.rs
  tests/it/io/parquet/read.rs
Labels: enhancement

#805 Reduced code duplication
  src/io/parquet/read/binary/basic.rs
  src/io/parquet/read/binary/dictionary.rs
  src/io/parquet/read/binary/mod.rs
  src/io/parquet/read/boolean/basic.rs
  src/io/parquet/read/boolean/mod.rs
  src/io/parquet/read/deserialize/mod.rs
  src/io/parquet/read/dictionary.rs
  src/io/parquet/read/fixed_size_binary/basic.rs
  src/io/parquet/read/fixed_size_binary/dictionary.rs
  src/io/parquet/read/fixed_size_binary/mod.rs
  src/io/parquet/read/mod.rs
  src/io/parquet/read/primitive/dictionary.rs
  src/io/parquet/read/primitive/mod.rs
Labels: testing

#806 Added support for reading parquet dictionary to arrow dictionary required
  src/io/parquet/read/dictionary.rs
  tests/it/io/parquet/mod.rs
Labels: enhancement

#808 Made crate `deny(missing_docs)`
  src/array/mod.rs
  src/bitmap/mod.rs
  src/buffer/mod.rs
  src/compute/mod.rs
  src/datatypes/mod.rs
  src/ffi/mod.rs
  src/io/avro/mod.rs
  src/io/csv/mod.rs
  src/io/flight/mod.rs
  src/io/ipc/mod.rs
  src/io/ipc/read/mod.rs
  src/io/ipc/read/reader.rs
  src/io/ipc/read/stream.rs
  src/io/ipc/write/serialize.rs
  src/io/ipc/write/writer.rs
  src/io/json/mod.rs
  src/io/json_integration/mod.rs
  src/io/json_integration/read/array.rs
  src/io/json_integration/read/mod.rs
  src/io/json_integration/write/mod.rs
  src/io/parquet/read/file.rs
  src/io/parquet/read/mod.rs
  src/io/parquet/read/statistics/binary.rs
  src/io/parquet/read/statistics/boolean.rs
  src/io/parquet/read/statistics/fixlen.rs
  src/io/parquet/read/statistics/primitive.rs
  src/io/parquet/write/file.rs
  src/lib.rs
  src/scalar/mod.rs
  src/types/mod.rs
Labels: documentation

#809 Added support to read parquet timestamps as dictionaries
  src/io/parquet/read/deserialize/mod.rs
  tests/it/io/parquet/read.rs
Labels: enhancement

#810 Added more tests
  tests/it/array/boolean/mod.rs
Labels: testing

#816 Fixed error in reading parquet
  src/io/parquet/read/binary/basic.rs
  src/io/parquet/read/primitive/basic.rs
Labels: bug

#818 Small improvement to deserializing fixed-len parquet statistics.
  src/io/parquet/read/statistics/fixlen.rs
  src/io/parquet/read/statistics/mod.rs
Labels: enhancement

#820 Improved flexibility of reading parquet
  examples/parquet_read_async.rs
  src/io/parquet/read/file.rs
  src/io/parquet/read/row_group.rs
Labels: enhancement

#821 Removed unused file
  src/io/parquet/read/record_batch.rs
Labels: no-changelog

#825 Added support to write largeUtf8/Binary to Avro
  src/io/avro/write/serialize.rs
Labels: enhancement

#826 Added support to read Avro's structs
  src/io/avro/read/deserialize.rs
  src/io/avro/read/nested.rs
  src/io/avro/read/schema.rs
  tests/it/io/avro/read.rs
Labels: feature

#827 Added support for pushdown projection in reading Avro
  benches/avro_read.rs
  examples/avro_read.rs
  examples/avro_read_async.rs
  src/io/avro/read/deserialize.rs
  src/io/avro/read/mod.rs
  src/io/avro/read/schema.rs
  src/io/avro/read_async/metadata.rs
  tests/it/io/avro/read.rs
  tests/it/io/avro/write.rs
  tests/it/io/avro/write_async.rs
Labels: feature

#831 Fixed error in reading plain pages from dict-encoded
  src/io/parquet/read/binary/basic.rs
Labels: bug

#832 Added support to read Arrow streams asynchronously
  Cargo.toml
  src/io/ipc/read/mod.rs
  src/io/ipc/read/schema.rs
  src/io/ipc/read/stream.rs
  src/io/ipc/read/stream_async.rs
  tests/it/io/ipc/mod.rs
  tests/it/io/ipc/read_stream_async.rs
Labels: feature

#833 Increased API consistency for COW and respective docs
  guide/src/high_level.md
  guide/src/low_level.md
  src/array/primitive/mod.rs
  src/array/utf8/mod.rs
  src/bitmap/immutable.rs
  src/buffer/immutable.rs
Labels: enhancement

#835 inline push
  src/array/utf8/mutable.rs
Labels: enhancement

#836 Fixed reading multiple dict pages
  src/io/parquet/read/dictionary.rs
Labels: no-changelog

#840 Fixed error in writing compressed IPC files
  src/io/ipc/compression.rs
  src/io/ipc/write/common_async.rs
  src/io/ipc/write/common_sync.rs
  src/io/ipc/write/serialize.rs
Labels: bug

#841 Bumped zstd
  Cargo.toml
Labels: enhancement

#842 Refactored (internal) fmt
  src/array/binary/fmt.rs
  src/array/binary/mod.rs
  src/array/boolean/fmt.rs
  src/array/boolean/mod.rs
  src/array/dictionary/fmt.rs
  src/array/dictionary/mod.rs
  src/array/display.rs
  src/array/fixed_size_binary/fmt.rs
  src/array/fixed_size_binary/mod.rs
  src/array/fixed_size_list/fmt.rs
  src/array/fixed_size_list/mod.rs
  src/array/fmt.rs
  src/array/list/fmt.rs
  src/array/list/mod.rs
  src/array/mod.rs
  src/array/primitive/display.rs
  src/array/primitive/fmt.rs
  src/array/primitive/mod.rs
  src/array/struct_/fmt.rs
  src/array/struct_/mod.rs
  src/array/union/fmt.rs
  src/array/union/mod.rs
  src/array/utf8/fmt.rs
  src/array/utf8/mod.rs
  src/io/print.rs
  tests/it/array/binary/mod.rs
  tests/it/array/boolean/mod.rs
  tests/it/array/fixed_size_binary/mod.rs
  tests/it/array/list/mod.rs
  tests/it/array/primitive/mod.rs
  tests/it/array/struct_/mod.rs
  tests/it/array/utf8/mod.rs
Labels: enhancement

#843 Removed un-needed `unsafe`
  src/compute/arithmetics/basic/div.rs
  src/compute/arithmetics/basic/rem.rs
  src/compute/arithmetics/mod.rs
Labels: testing

#844 Fixed error in extending binary parquet
  src/io/parquet/read/binary/utils.rs
Labels: bug, no-changelog

#845 DRY parquet reading
  src/io/parquet/read/binary/basic.rs
  src/io/parquet/read/binary/nested.rs
  src/io/parquet/read/boolean/basic.rs
  src/io/parquet/read/boolean/nested.rs
  src/io/parquet/read/deserialize/mod.rs
  src/io/parquet/read/dictionary.rs
  src/io/parquet/read/fixed_size_binary/basic.rs
  src/io/parquet/read/mod.rs
  src/io/parquet/read/nested_utils.rs
  src/io/parquet/read/primitive/basic.rs
  src/io/parquet/read/primitive/mod.rs
  src/io/parquet/read/primitive/nested.rs
  src/io/parquet/read/primitive/utils.rs
  src/io/parquet/read/utils.rs
Labels: enhancement

#855 Fixed error in writing compressed IPC arrow
  src/io/ipc/write/serialize.rs
Labels: bug

#854 Simplified API for FFI
  arrow-pyarrow-integration-testing/src/lib.rs
  examples/ffi.rs
  src/array/binary/ffi.rs
  src/array/boolean/ffi.rs
  src/array/fixed_size_binary/ffi.rs
  src/array/fixed_size_list/ffi.rs
  src/array/list/ffi.rs
  src/array/map/ffi.rs
  src/array/null.rs
  src/array/primitive/ffi.rs
  src/array/struct_/ffi.rs
  src/array/union/ffi.rs
  src/array/utf8/ffi.rs
  src/ffi/array.rs
  src/ffi/ffi.rs
  src/ffi/mod.rs
  src/ffi/schema.rs
  tests/it/ffi.rs
Labels: backwards-incompatible

#856 Bumped crc
  Cargo.toml
  src/io/avro/read/decompress.rs
  src/io/avro/write/compress.rs
Labels: enhancement

#857 Added support to the Arrow C stream interface (read and write)
  README.md
  arrow-pyarrow-integration-testing/README.md
  arrow-pyarrow-integration-testing/pyproject.toml
  arrow-pyarrow-integration-testing/src/c_stream.rs
  arrow-pyarrow-integration-testing/src/lib.rs
  arrow-pyarrow-integration-testing/tests/test_c_stream.py
  examples/ffi.rs
  src/buffer/bytes.rs
  src/ffi/array.rs
  src/ffi/ffi.rs
  src/ffi/generated.rs
  src/ffi/mod.rs
  src/ffi/schema.rs
  src/ffi/stream.rs
  tests/it/ffi/data.rs
  tests/it/ffi/mod.rs
  tests/it/ffi/stream.rs
Labels: feature

#860 Improved documentation
  benches/avro_read.rs
  benches/write_parquet.rs
  examples/ffi.rs
  examples/parquet_read_async.rs
  src/bitmap/bitmap_ops.rs
  src/bitmap/mutable.rs
  src/compute/like.rs
  src/compute/sort/mod.rs
  src/io/ipc/read/common.rs
  src/io/json/read/infer_schema.rs
  src/io/json_integration/read/array.rs
  src/io/parquet/read/schema/convert.rs
  src/io/parquet/read/statistics/mod.rs
  src/io/parquet/write/dictionary.rs
  src/types/bit_chunk.rs
  tests/it/compute/sort/mod.rs
Labels: documentation

#847 Simplified compute (lower/upper)
  Cargo.toml
  src/compute/lower.rs
  src/compute/mod.rs
  src/compute/regex_match.rs
  src/compute/upper.rs
  src/compute/utf8.rs
  src/compute/utils.rs
  src/error.rs
  tests/it/compute/lower.rs
  tests/it/compute/mod.rs
  tests/it/compute/upper.rs
  tests/it/compute/utf8.rs
Labels: backwards-incompatible

#862 Fixed reading parquet with timezone
  parquet_integration/write_parquet.py
  src/io/parquet/read/deserialize/mod.rs
  tests/it/io/parquet/mod.rs
  tests/it/io/parquet/read.rs
Labels: bug

#864 Simplified API for writing to JSON
  benches/write_json.rs
  examples/json_write.rs
  src/io/json/write/mod.rs
  src/io/json/write/serialize.rs
  tests/it/io/json/mod.rs
  tests/it/io/json/write.rs
Labels: backwards-incompatible

#866 change csv-writer
  Cargo.toml
  benches/write_csv.rs
  examples/csv_write.rs
  examples/csv_write_parallel.rs
  src/io/csv/write/mod.rs
  src/io/csv/write/serialize.rs
  tests/it/io/csv/write.rs
Labels: backwards-incompatible

#867 Fixed json writing of dates and datetimes
  src/io/json/write/serialize.rs
  tests/it/io/json/write.rs
Labels: bug

#870 Refactored JSON IO (better support for JSON and NDJSON)
  benches/write_json.rs
  examples/json_read.rs
  examples/json_write.rs
  examples/ndjson_read.rs
  examples/ndjson_write.rs
  guide/src/README.md
  guide/src/io/json_read.md
  guide/src/io/json_write.md
  src/io/json/read/deserialize.rs
  src/io/json/read/infer_schema.rs
  src/io/json/read/iterator.rs
  src/io/json/read/mod.rs
  src/io/json/write/format.rs
  src/io/json/write/mod.rs
  src/io/json/write/serialize.rs
  src/io/mod.rs
  src/io/ndjson/mod.rs
  src/io/ndjson/read/deserialize.rs
  src/io/ndjson/read/file.rs
  src/io/ndjson/read/mod.rs
  src/io/ndjson/write/mod.rs
  tests/it/io/json/mod.rs
  tests/it/io/json/read.rs
  tests/it/io/json/write.rs
  tests/it/io/mod.rs
  tests/it/io/ndjson/mod.rs
  tests/it/io/ndjson/read.rs
Labels: enhancement
