Repository jorgecarleitao/arrow2, pull requests merged in 2022-07, with the labels that each got.

#1134 chore: Make rust clippy happy
  examples/ipc_file_read.rs
  src/bitmap/assign_ops.rs
  src/chunk.rs
  src/io/avro/mod.rs
  src/io/avro/read/decompress.rs
  src/io/parquet/read/deserialize/nested_utils.rs
  src/io/parquet/read/deserialize/primitive/basic.rs
  src/io/parquet/read/deserialize/primitive/nested.rs
  src/io/parquet/read/statistics/mod.rs
  src/lib.rs
  src/scalar/binary.rs
  src/scalar/boolean.rs
  src/scalar/fixed_size_binary.rs
  src/scalar/primitive.rs
  src/scalar/utf8.rs
Labels: enhancement

#1129 Change signature of PrimitiveScalar::value to return reference
  src/compute/arithmetics/decimal/div.rs
  src/compute/arithmetics/decimal/mul.rs
  src/compute/arithmetics/mod.rs
  src/compute/arithmetics/time.rs
  src/scalar/primitive.rs
  tests/it/array/union.rs
  tests/it/scalar/primitive.rs
Labels: backwards-incompatible

#1136 Simplified code in flight integration tests
  integration-testing/Cargo.toml
  integration-testing/README.md
  integration-testing/src/bin/arrow-json-integration-test.rs
  integration-testing/src/flight_client_scenarios.rs
  integration-testing/src/flight_client_scenarios/integration_test.rs
  integration-testing/src/flight_client_scenarios/middleware.rs
  integration-testing/src/flight_client_scenarios/mod.rs
  integration-testing/src/flight_server_scenarios/auth_basic_proto.rs
  integration-testing/src/flight_server_scenarios/integration_test.rs
  integration-testing/src/flight_server_scenarios/mod.rs
  integration-testing/src/lib.rs
Labels: testing

#1138 Updated license wording
  LICENSE
  license.py
Labels: documentation

#1139 Fixed panic in deserializing nested statistics
  src/io/parquet/read/statistics/mod.rs
  tests/it/io/parquet/mod.rs
Labels: bug

#1137 Improved dictionary invariants
  src/array/dictionary/ffi.rs
  src/array/dictionary/fmt.rs
  src/array/dictionary/iterator.rs
  src/array/dictionary/mod.rs
  src/array/dictionary/mutable.rs
  src/array/equal/dictionary.rs
  src/array/equal/mod.rs
  src/array/growable/dictionary.rs
  src/array/ord.rs
  src/array/specification.rs
  src/compute/arithmetics/mod.rs
  src/compute/cast/dictionary_to.rs
  src/compute/sort/utf8.rs
  src/compute/take/dict.rs
  src/io/avro/read/nested.rs
  src/io/csv/write/serialize.rs
  src/io/ipc/read/array/dictionary.rs
  src/io/ipc/read/deserialize.rs
  src/io/json/read/deserialize.rs
  src/io/json_integration/read/array.rs
  src/io/parquet/read/deserialize/binary/dictionary.rs
  src/io/parquet/read/deserialize/dictionary.rs
  src/io/parquet/read/deserialize/fixed_size_binary/dictionary.rs
  src/io/parquet/read/deserialize/primitive/dictionary.rs
  src/io/parquet/read/statistics/dictionary.rs
  src/io/parquet/write/dictionary.rs
  tests/it/array/dictionary/mod.rs
  tests/it/array/equal/dictionary.rs
  tests/it/array/growable/dictionary.rs
  tests/it/array/growable/mod.rs
  tests/it/compute/arithmetics/mod.rs
  tests/it/io/avro/read.rs
  tests/it/io/csv/write.rs
  tests/it/io/parquet/mod.rs
  tests/it/io/parquet/read_indexes.rs
  tests/it/io/print.rs
Labels: backwards-incompatible

#1140 Fixed reading arrays from parquet with required children
  parquet_integration/bench_compute.py
  parquet_integration/write_parquet.py
  src/io/parquet/read/deserialize/binary/nested.rs
  src/io/parquet/read/deserialize/boolean/nested.rs
  src/io/parquet/read/deserialize/nested_utils.rs
  src/io/parquet/read/deserialize/primitive/basic.rs
  src/io/parquet/read/deserialize/primitive/nested.rs
  src/io/parquet/read/deserialize/utils.rs
  tests/it/io/parquet/mod.rs
  tests/it/io/parquet/read.rs
Labels: bug

#1142 Reduced bound checks
  src/array/growable/dictionary.rs
  src/array/growable/list.rs
  src/array/growable/utf8.rs
Labels: enhancement

#1149 fix ipc projection
  src/io/ipc/read/common.rs
Labels: bug

#1148 Use ahash by default
  Cargo.toml
  arrow-parquet-integration-testing/src/main.rs
  integration-testing/src/lib.rs
  src/array/union/mod.rs
  src/compute/like.rs
  src/compute/merge_sort/mod.rs
  src/compute/regex_match.rs
  src/io/avro/mod.rs
  src/io/avro/read/header.rs
  src/io/avro/read/util.rs
  src/io/avro/read_async/metadata.rs
  src/io/avro/write/header.rs
  src/io/csv/read/infer_schema.rs
  src/io/csv/read_async/infer_schema.rs
  src/io/csv/utils.rs
  src/io/ipc/read/common.rs
  src/io/ipc/read/file_async.rs
  src/io/ipc/read/mod.rs
  src/io/ipc/read/reader.rs
  src/io/ipc/read/stream.rs
  src/io/json_integration/read/array.rs
  src/io/parquet/write/sink.rs
  src/lib.rs
  tests/it/io/ipc/common.rs
  tests/it/io/parquet/write_async.rs
Labels: enhancement

#1143 fix casting dictionary keys
  src/compute/cast/dictionary_to.rs
  tests/it/compute/cast.rs
Labels: bug

#1150 Fixed error in reading `Struct<List<...>>` from parquet
  parquet_integration/write_parquet.py
  src/array/struct_/mod.rs
  src/io/parquet/read/deserialize/nested_utils.rs
  tests/it/io/parquet/mod.rs
  tests/it/io/parquet/read.rs
Labels: bug

#1151 Added example reading Avro produced by Kafka
  examples/avro_kafka.rs
Labels: documentation

#1141 Moved `Bytes` to own crate
  Cargo.toml
  src/array/binary/ffi.rs
  src/array/boolean/ffi.rs
  src/array/dictionary/ffi.rs
  src/array/ffi.rs
  src/array/fixed_size_binary/ffi.rs
  src/array/fixed_size_list/ffi.rs
  src/array/list/ffi.rs
  src/array/map/ffi.rs
  src/array/null.rs
  src/array/primitive/ffi.rs
  src/array/struct_/ffi.rs
  src/array/union/ffi.rs
  src/array/utf8/ffi.rs
  src/bitmap/immutable.rs
  src/buffer/bytes.rs
  src/buffer/immutable.rs
  src/buffer/mod.rs
  src/ffi/array.rs
Labels: enhancement

#1153 Removed un-needed indirection
  src/buffer/mod.rs
  src/ffi/array.rs
Labels: enhancement

#1156 Bumped MIRI
  .github/workflows/test.yml
Labels: testing

#1154 Improved checks to safety invariants in FFI
  src/ffi/array.rs
Labels: enhancement

#1158 Added more tests
  tests/it/io/parquet/mod.rs
Labels: testing

#1160 Minor cleanup of internal namings
  src/io/flight/mod.rs
  src/io/ipc/read/common.rs
  src/io/ipc/read/schema.rs
Labels: documentation

#1162 Made kafka schema_id `u32` in example
  examples/avro_kafka.rs
Labels: testing

#1163 release memory on predicate with 0% selectivity
  src/compute/filter.rs
Labels: bug

#1164 Improved docs
  src/buffer/immutable.rs
Labels: documentation

#1179 Improved error message
  src/array/specification.rs
Labels: enhancement

#1176 use `FnOnce` for `PrimitiveArray::apply_validity`
  src/array/primitive/mod.rs
Labels: bug

#1175 Added support to read and write nested dictionaries to parquet
  examples/parquet_write.rs
  src/array/primitive/mod.rs
  src/io/parquet/read/deserialize/binary/dictionary.rs
  src/io/parquet/read/deserialize/binary/mod.rs
  src/io/parquet/read/deserialize/binary/nested.rs
  src/io/parquet/read/deserialize/boolean/mod.rs
  src/io/parquet/read/deserialize/boolean/nested.rs
  src/io/parquet/read/deserialize/dictionary/mod.rs
  src/io/parquet/read/deserialize/dictionary/nested.rs
  src/io/parquet/read/deserialize/fixed_size_binary/dictionary.rs
  src/io/parquet/read/deserialize/fixed_size_binary/mod.rs
  src/io/parquet/read/deserialize/mod.rs
  src/io/parquet/read/deserialize/nested_utils.rs
  src/io/parquet/read/deserialize/primitive/dictionary.rs
  src/io/parquet/read/deserialize/primitive/mod.rs
  src/io/parquet/read/deserialize/primitive/nested.rs
  src/io/parquet/write/binary/nested.rs
  src/io/parquet/write/boolean/nested.rs
  src/io/parquet/write/dictionary.rs
  src/io/parquet/write/mod.rs
  src/io/parquet/write/pages.rs
  src/io/parquet/write/primitive/nested.rs
  src/io/parquet/write/utf8/nested.rs
  tests/it/io/parquet/mod.rs
  tests/it/io/parquet/read_indexes.rs
Labels: enhancement

#1181 Fixed reading stats from int96 parquet
  src/io/parquet/read/statistics/mod.rs
Labels: bug

#1182 Fixed error in counting items in nested parquet
  src/io/parquet/read/deserialize/nested_utils.rs
Labels: bug

#1180 Fixed limit pushdown in parquet
  src/io/parquet/read/deserialize/binary/basic.rs
  src/io/parquet/read/deserialize/binary/dictionary.rs
  src/io/parquet/read/deserialize/binary/nested.rs
  src/io/parquet/read/deserialize/boolean/basic.rs
  src/io/parquet/read/deserialize/boolean/nested.rs
  src/io/parquet/read/deserialize/dictionary/mod.rs
  src/io/parquet/read/deserialize/dictionary/nested.rs
  src/io/parquet/read/deserialize/fixed_size_binary/basic.rs
  src/io/parquet/read/deserialize/fixed_size_binary/dictionary.rs
  src/io/parquet/read/deserialize/mod.rs
  src/io/parquet/read/deserialize/nested_utils.rs
  src/io/parquet/read/deserialize/null.rs
  src/io/parquet/read/deserialize/primitive/basic.rs
  src/io/parquet/read/deserialize/primitive/dictionary.rs
  src/io/parquet/read/deserialize/primitive/nested.rs
  src/io/parquet/read/deserialize/simple.rs
  src/io/parquet/read/deserialize/utils.rs
  src/io/parquet/read/file.rs
  src/io/parquet/read/row_group.rs
  src/io/print.rs
  tests/it/io/parquet/integration.rs
  tests/it/io/parquet/mod.rs
  tests/it/io/parquet/read_indexes.rs
Labels: bug

#1183 Simplified code
  src/io/parquet/read/deserialize/binary/dictionary.rs
  src/io/parquet/read/deserialize/binary/mod.rs
  src/io/parquet/read/deserialize/binary/nested.rs
  src/io/parquet/read/deserialize/boolean/mod.rs
  src/io/parquet/read/deserialize/boolean/nested.rs
  src/io/parquet/read/deserialize/fixed_size_binary/dictionary.rs
  src/io/parquet/read/deserialize/fixed_size_binary/mod.rs
  src/io/parquet/read/deserialize/mod.rs
  src/io/parquet/read/deserialize/nested.rs
  src/io/parquet/read/deserialize/primitive/dictionary.rs
  src/io/parquet/read/deserialize/primitive/mod.rs
  src/io/parquet/read/deserialize/primitive/nested.rs
Labels: testing

#1188 Fixed error in decoding nested multi-page columns from parquet
  src/array/struct_/mod.rs
  src/io/parquet/read/deserialize/nested_utils.rs
  src/io/parquet/read/deserialize/utils.rs
Labels: bug

#1192 Fixed error not implemented error when reading plain, after-dict pages for fix-len-binary from parquet
  src/io/parquet/read/deserialize/fixed_size_binary/basic.rs
Labels: bug

#1190 Improved performance of reading Binary from parquet
  src/io/parquet/read/deserialize/binary/utils.rs
Labels: enhancement

#1198 Temporary skip decimal256 integration tests
  integration-testing/unskip.patch
Labels: testing

#1189 Added support to read ORC
  .github/workflows/coverage.yml
  .github/workflows/test.yml
  Cargo.toml
  DEVELOPMENT.md
  examples/orc_read.rs
  src/io/mod.rs
  src/io/orc/mod.rs
  src/io/orc/read/mod.rs
  src/types/native.rs
  tests/it/io/mod.rs
  tests/it/io/orc/mod.rs
  tests/it/io/orc/read.rs
  tests/it/io/orc/write.py
Labels: feature
