Repository jorgecarleitao/arrow2, pull requests merged in 2022-08, with the labels that each got.

#1202 Added `MutableArray::reserve`
  src/array/binary/mutable.rs
  src/array/boolean/mutable.rs
  src/array/dictionary/mutable.rs
  src/array/fixed_size_binary/mutable.rs
  src/array/fixed_size_list/mutable.rs
  src/array/list/mutable.rs
  src/array/mod.rs
  src/array/primitive/mutable.rs
  src/array/utf8/mutable.rs
  src/io/avro/read/nested.rs
  src/io/parquet/read/statistics/dictionary.rs
  src/io/parquet/read/statistics/list.rs
  src/io/parquet/read/statistics/map.rs
  src/io/parquet/read/statistics/struct_.rs
Labels: enhancement

#1201 Write 64bit aligned IPC files
  src/io/ipc/write/common.rs
  src/io/ipc/write/common_async.rs
  src/io/ipc/write/common_sync.rs
  src/io/ipc/write/serialize.rs
Labels: feature

#1203 Removed println :(
  src/io/orc/read/mod.rs
Labels: bug

#1204 Fix escaped like wildcards
  Cargo.toml
  src/compute/like.rs
  tests/it/compute/like.rs
Labels: bug

#1197 Added support to mmap IPC format
  .github/workflows/test.yml
  examples/ipc_file_mmap.rs
  guide/src/SUMMARY.md
  guide/src/io/ipc_mmap.md
  src/array/list/mod.rs
  src/ffi/array.rs
  src/ffi/mmap.rs
  src/ffi/mod.rs
  src/io/ipc/mod.rs
  src/io/ipc/read/common.rs
  src/io/ipc/read/file_async.rs
  src/io/ipc/read/mod.rs
  src/io/ipc/read/reader.rs
  src/lib.rs
  src/mmap/mod.rs
  tests/it/io/ipc/mmap.rs
  tests/it/io/ipc/mod.rs
  tests/it/io/ipc/write/mod.rs
Labels: feature

#1205 Improved API of `mmap`
  examples/ipc_file_mmap.rs
  src/ffi/mmap.rs
  src/io/ipc/read/reader.rs
  src/mmap/mod.rs
  tests/it/io/ipc/mmap.rs
Labels: enhancement

#1199 Migrated Avro code to avro-schema repo
  Cargo.toml
  benches/avro_read.rs
  examples/avro_kafka.rs
  examples/avro_read.rs
  examples/avro_read_async.rs
  examples/avro_write.rs
  src/io/avro/mod.rs
  src/io/avro/read/block.rs
  src/io/avro/read/decompress.rs
  src/io/avro/read/deserialize.rs
  src/io/avro/read/header.rs
  src/io/avro/read/mod.rs
  src/io/avro/read/schema.rs
  src/io/avro/read/util.rs
  src/io/avro/read_async/block.rs
  src/io/avro/read_async/metadata.rs
  src/io/avro/read_async/mod.rs
  src/io/avro/read_async/utils.rs
  src/io/avro/write/block.rs
  src/io/avro/write/compress.rs
  src/io/avro/write/header.rs
  src/io/avro/write/mod.rs
  src/io/avro/write/schema.rs
  src/io/avro/write/serialize.rs
  src/io/avro/write/util.rs
  src/io/avro/write_async/block.rs
  src/io/avro/write_async/mod.rs
  tests/it/io/avro/read.rs
  tests/it/io/avro/read_async.rs
  tests/it/io/avro/write.rs
  tests/it/io/avro/write_async.rs
Labels: backwards-incompatible

#1211 Fix some doc links/typos
  src/array/binary/mod.rs
  src/array/fixed_size_list/mod.rs
  src/array/growable/mod.rs
  src/array/list/mod.rs
  src/array/list/mutable.rs
  src/array/mod.rs
Labels: documentation

#1196 Added `MutableStructArray`
  src/array/mod.rs
  src/array/struct_/mod.rs
  src/array/struct_/mutable.rs
  tests/it/array/struct_/mod.rs
  tests/it/array/struct_/mutable.rs
Labels: feature

#1213 `FileSink` now closes the underlying writer.
  src/io/parquet/write/sink.rs
Labels: bug

#1212 Fixed JSON infer order
  Cargo.toml
  src/io/json/read/infer_schema.rs
  tests/it/io/ndjson/mod.rs
Labels: bug

#1208 Simpler IPC API
  integration-testing/Cargo.toml
  integration-testing/src/flight_client_scenarios/integration_test.rs
  integration-testing/src/flight_server_scenarios/integration_test.rs
  src/io/flight/mod.rs
  src/io/ipc/read/file.rs
  src/io/ipc/read/file_async.rs
  src/io/ipc/read/mod.rs
  src/io/ipc/read/reader.rs
  src/mmap/mod.rs
Labels: backwards-incompatible

#1214 Updated integration test
  integration-testing/unskip.patch
Labels: testing

#1210 Fixed StackOverflow in many row groups
  src/io/parquet/read/file.rs
  tests/it/io/parquet/mod.rs
Labels: bug

#1215 Added support for parquet sidecar to `FileReader`
  benches/read_parquet.rs
  examples/parquet_read.rs
  examples/parquet_read_async.rs
  examples/s3/src/main.rs
  src/datatypes/schema.rs
  src/io/parquet/read/file.rs
  src/io/parquet/read/row_group.rs
  tests/it/io/parquet/mod.rs
  tests/it/io/parquet/read.rs
  tests/it/io/parquet/read_indexes.rs
  tests/it/io/parquet/write_async.rs
Labels: feature

#1217 Removed `Count` (parquet statistics)
  src/io/parquet/read/statistics/mod.rs
  tests/it/io/parquet/mod.rs
Labels: backwards-incompatible

#1185 Delayed dict
  Cargo.toml
  benches/read_parquet.rs
  src/io/parquet/read/deserialize/README.md
  src/io/parquet/read/deserialize/binary/basic.rs
  src/io/parquet/read/deserialize/binary/dictionary.rs
  src/io/parquet/read/deserialize/binary/nested.rs
  src/io/parquet/read/deserialize/binary/utils.rs
  src/io/parquet/read/deserialize/boolean/basic.rs
  src/io/parquet/read/deserialize/boolean/nested.rs
  src/io/parquet/read/deserialize/dictionary/mod.rs
  src/io/parquet/read/deserialize/dictionary/nested.rs
  src/io/parquet/read/deserialize/fixed_size_binary/basic.rs
  src/io/parquet/read/deserialize/fixed_size_binary/dictionary.rs
  src/io/parquet/read/deserialize/mod.rs
  src/io/parquet/read/deserialize/nested.rs
  src/io/parquet/read/deserialize/nested_utils.rs
  src/io/parquet/read/deserialize/null.rs
  src/io/parquet/read/deserialize/primitive/basic.rs
  src/io/parquet/read/deserialize/primitive/dictionary.rs
  src/io/parquet/read/deserialize/primitive/nested.rs
  src/io/parquet/read/deserialize/simple.rs
  src/io/parquet/read/deserialize/utils.rs
  src/io/parquet/read/mod.rs
  src/io/parquet/read/row_group.rs
  src/io/parquet/write/dictionary.rs
  src/io/parquet/write/mod.rs
  src/io/parquet/write/utils.rs
Labels: enhancement

#1220 Added utf8 <> binary cast
  src/compute/cast/binary_to.rs
  src/compute/cast/mod.rs
  src/compute/cast/utf8_to.rs
  tests/it/compute/cast.rs
Labels: enhancement

#1221 Reduced binary size
  src/io/flight/mod.rs
  src/io/ipc/read/deserialize.rs
  src/io/ipc/read/schema.rs
  src/io/orc/read/mod.rs
Labels: enhancement

#1225 Fix a typo in the docs
  src/bitmap/immutable.rs
Labels: documentation

#1216 Exposed parquet indexed page filtering to `FileReader`
  benches/read_parquet.rs
  examples/parquet_read.rs
  examples/parquet_read_async.rs
  src/io/ipc/read/mod.rs
  src/io/parquet/read/file.rs
  src/io/parquet/read/indexes/binary.rs
  src/io/parquet/read/indexes/boolean.rs
  src/io/parquet/read/indexes/fixed_len_binary.rs
  src/io/parquet/read/indexes/mod.rs
  src/io/parquet/read/indexes/primitive.rs
  src/io/parquet/read/mod.rs
  src/io/parquet/read/row_group.rs
  src/io/parquet/read/statistics/dictionary.rs
  tests/it/io/parquet/mod.rs
  tests/it/io/parquet/read.rs
  tests/it/io/parquet/read_indexes.rs
  tests/it/io/parquet/write_async.rs
Labels: backwards-incompatible

#1228 Added support for decoding delta-length-encoded binary (parquet)
  src/io/parquet/read/deserialize/binary/basic.rs
  src/io/parquet/read/deserialize/binary/utils.rs
  src/io/parquet/write/binary/basic.rs
  tests/it/io/parquet/read_indexes.rs
  tests/it/io/parquet/write.rs
Labels: feature

#1229 Removed unneeded code
  src/io/parquet/write/nested/mod.rs
Labels: enhancement

#1226 Added support to read and write Parquet's delta-bitpacked (integer encoding)
  Cargo.toml
  arrow-parquet-integration-testing/main.py
  arrow-parquet-integration-testing/main_spark.py
  arrow-parquet-integration-testing/src/main.rs
  src/io/parquet/mod.rs
  src/io/parquet/read/deserialize/binary/basic.rs
  src/io/parquet/read/deserialize/binary/nested.rs
  src/io/parquet/read/deserialize/boolean/nested.rs
  src/io/parquet/read/deserialize/dictionary/mod.rs
  src/io/parquet/read/deserialize/dictionary/nested.rs
  src/io/parquet/read/deserialize/fixed_size_binary/basic.rs
  src/io/parquet/read/deserialize/nested_utils.rs
  src/io/parquet/read/deserialize/primitive/basic.rs
  src/io/parquet/read/deserialize/primitive/integer.rs
  src/io/parquet/read/deserialize/primitive/mod.rs
  src/io/parquet/read/deserialize/primitive/nested.rs
  src/io/parquet/read/deserialize/simple.rs
  src/io/parquet/read/deserialize/utils.rs
  src/io/parquet/write/dictionary.rs
  src/io/parquet/write/mod.rs
  src/io/parquet/write/nested/mod.rs
  src/io/parquet/write/primitive/basic.rs
  src/io/parquet/write/primitive/mod.rs
  src/io/parquet/write/primitive/nested.rs
  src/io/parquet/write/row_group.rs
  tests/it/io/parquet/read_indexes.rs
  tests/it/io/parquet/write.rs
Labels: feature

#1233 Improved github page generation
  .github/workflows/docs.yml
  README.md
Labels: documentation

#1237 doc(): fix small typo in error message for impl StructArray
  src/array/struct_/mod.rs
Labels: documentation
