Repository jorgecarleitao/arrow2, pull requests merged in 2022-01, with the labels that each got.

#722 Made all panics in IPC read errors
  src/error.rs
  src/io/flight/mod.rs
  src/io/ipc/compression.rs
  src/io/ipc/read/array/binary.rs
  src/io/ipc/read/array/boolean.rs
  src/io/ipc/read/array/dictionary.rs
  src/io/ipc/read/array/fixed_size_binary.rs
  src/io/ipc/read/array/fixed_size_list.rs
  src/io/ipc/read/array/list.rs
  src/io/ipc/read/array/map.rs
  src/io/ipc/read/array/null.rs
  src/io/ipc/read/array/primitive.rs
  src/io/ipc/read/array/struct_.rs
  src/io/ipc/read/array/union.rs
  src/io/ipc/read/array/utf8.rs
  src/io/ipc/read/common.rs
  src/io/ipc/read/deserialize.rs
  src/io/ipc/read/read_basic.rs
  src/io/ipc/read/reader.rs
  src/io/ipc/read/schema.rs
  src/io/ipc/read/stream.rs
  src/io/parquet/read/schema/metadata.rs
Labels: bug

#723 Added `and_scalar` and `or_scalar` for boolean kleene
  src/compute/boolean_kleene.rs
  tests/it/compute/boolean_kleene.rs
Labels: feature

#724 More tests to CSV writing
  tests/it/io/csv/write.rs
Labels: testing

#730 Add benchmark check
  .github/workflows/test.yml
  benches/arithmetic_kernels.rs
  benches/avro_read.rs
  benches/filter_kernels.rs
  benches/write_csv.rs
  benches/write_ipc.rs
  benches/write_parquet.rs
Labels: testing

#731 Updated patch for integration test
  integration-testing/unskip.patch
Labels: testing

#734 Added support to write interval to Avro
  src/io/avro/write/serialize.rs
  tests/it/io/avro/write.rs
Labels: feature

#736 Added support to write Avro async
  src/io/avro/mod.rs
  src/io/avro/write/mod.rs
  src/io/avro/write_async/block.rs
  src/io/avro/write_async/mod.rs
  tests/it/io/avro/mod.rs
  tests/it/io/avro/write.rs
  tests/it/io/avro/write_async.rs
Labels: feature

#740 Added integration tests for writing compressed parquet
  arrow-parquet-integration-testing/Cargo.toml
  arrow-parquet-integration-testing/main.py
  arrow-parquet-integration-testing/main_spark.py
  arrow-parquet-integration-testing/src/main.rs
Labels: testing

#735 Improved README
  README.md
Labels: documentation

#742 Improved json tests
  tests/it/io/json/mod.rs
  tests/it/io/json/read.rs
Labels: testing

#744 fix bug in any kernel
  src/compute/boolean.rs
  tests/it/compute/boolean.rs
Labels: no-changelog

#746 Added support to compare intervals
  src/compute/comparison/mod.rs
  src/compute/comparison/primitive.rs
  src/compute/comparison/simd/mod.rs
  src/compute/comparison/simd/native.rs
  src/compute/comparison/simd/packed.rs
  src/compute/nullif.rs
  tests/it/compute/comparison.rs
Labels: feature

#748 Replaced assert by error in IPC read
  src/io/ipc/read/read_basic.rs
Labels: bug

#749 Made IO `#[forbid(unsafe)]`
  Cargo.toml
  src/io/avro/mod.rs
  src/io/csv/mod.rs
  src/io/ipc/read/read_basic.rs
  src/io/ipc/write/serialize.rs
  src/io/json/mod.rs
  src/io/mod.rs
  src/io/parquet/read/primitive/basic.rs
  src/io/parquet/read/primitive/nested.rs
  src/io/parquet/read/primitive/utils.rs
  src/types/native.rs
Labels: enhancement

#752 Migrated to latest parquet2
  Cargo.toml
  src/io/parquet/write/record_batch.rs
  src/io/parquet/write/stream.rs
Labels: backwards-incompatible

#753 Refactored `nullif`
  src/compute/comparison/mod.rs
  src/compute/comparison/primitive.rs
  src/compute/nullif.rs
  src/compute/utils.rs
Labels: backwards-incompatible

#755 Replaced un-needed `unsafe`
  src/compute/aggregate/min_max.rs
Labels: enhancement

#756 Remove un-needed `unsafe`
  src/compute/cast/mod.rs
  src/compute/cast/utf8_to.rs
Labels: enhancement

#757 Added iterator of values of `FixedBinaryArray`
  src/array/fixed_size_binary/iterator.rs
Labels: enhancement

#758 Added support to deserialize JSON (!= NDJSON)
  examples/json_read.rs
  examples/ndjson_read.rs
  guide/src/io/README.md
  guide/src/io/json_read.md
  src/io/json/read/deserialize.rs
  src/io/json/read/infer_schema.rs
  src/io/json/read/mod.rs
  tests/it/io/json/read.rs
Labels: feature

#760 Simplified code
  src/array/binary/mutable.rs
  src/array/mod.rs
  src/array/physical_binary.rs
  src/array/utf8/mutable.rs
Labels: enhancement

#761 Added support to cast decimal
  src/compute/cast/decimal_to.rs
  src/compute/cast/mod.rs
  src/compute/cast/primitive_to.rs
  tests/it/compute/cast.rs
Labels: feature

#762 Described how to run part of the tests
  DEVELOPMENT.md
  src/io/parquet/read/schema/metadata.rs
Labels: documentation

#763 Fixed clippy (coming from 1.58)
  src/ffi/ffi.rs
Labels: documentation

#767 Fixed bug on API for Arrow stream
  integration-testing/src/bin/arrow-file-to-stream.rs
  src/io/ipc/write/stream.rs
  tests/it/io/ipc/write/stream.rs
Labels: no-changelog

#779 Fixed CI for SIMD
  .github/workflows/test.yml
Labels: testing

#778 Added support to read and write float dict from parquet
  src/io/parquet/read/mod.rs
  src/io/parquet/write/dictionary.rs
  tests/it/io/parquet/mod.rs
Labels: enhancement

#781 Read dict binary from parquet
  src/io/parquet/read/binary/dictionary.rs
  src/io/parquet/read/mod.rs
  tests/it/io/parquet/mod.rs
Labels: enhancement

#686 Added support for compare dictionary-encoded with scalar
  Cargo.toml
  src/compute/comparison/mod.rs
  src/compute/take/mod.rs
  src/types/index.rs
  tests/it/compute/comparison.rs
Labels: feature

#780 Allowed passing `None` as ipc_fields in flight API
  integration-testing/src/flight_client_scenarios/integration_test.rs
  integration-testing/src/flight_server_scenarios/integration_test.rs
  src/io/flight/mod.rs
Labels: bug

#785 DRY parquet module
  src/io/parquet/read/binary/basic.rs
  src/io/parquet/read/binary/dictionary.rs
  src/io/parquet/read/binary/mod.rs
  src/io/parquet/read/binary/nested.rs
  src/io/parquet/read/binary/utils.rs
  src/io/parquet/read/boolean/basic.rs
  src/io/parquet/read/fixed_size_binary.rs
  src/io/parquet/read/fixed_size_binary/mod.rs
  src/io/parquet/read/fixed_size_binary/utils.rs
  src/io/parquet/read/primitive/basic.rs
  src/io/parquet/read/primitive/dictionary.rs
  src/io/parquet/read/utils.rs
Labels: enhancement

#788 Added scalar bitwise ops
  src/compute/bitwise.rs
Labels: enhancement

#737 Simplified avro reading and added more tests
  src/io/avro/read/schema.rs
  src/io/avro/write/serialize.rs
  tests/it/io/avro/write.rs
Labels: testing
