Repository jorgecarleitao/arrow2, pull requests merged in 2022-05, with the labels that each got.

#974 Fixed empty reader panic for NDJSON type infer
  src/io/json/read/infer_schema.rs
  src/io/ndjson/read/deserialize.rs
  src/io/ndjson/read/file.rs
  tests/it/io/ndjson/read.rs
Labels: bug

#979 Added support Parquet deserialize LargeList and Uint data types
  src/io/parquet/read/deserialize/mod.rs
Labels: enhancement

#978 Added support to read nested binary from parquet
  src/io/parquet/read/deserialize/mod.rs
Labels: bug

#982 Fixed decoding Binary Plain pages with dictionary pages
  src/io/parquet/read/deserialize/binary/nested.rs
Labels: bug

#984 Fixed error in writing `ListArray` to parquet
  parquet_integration/write_parquet.py
  src/io/parquet/write/binary/basic.rs
  src/io/parquet/write/binary/nested.rs
  src/io/parquet/write/boolean/basic.rs
  src/io/parquet/write/boolean/nested.rs
  src/io/parquet/write/dictionary.rs
  src/io/parquet/write/fixed_len_bytes.rs
  src/io/parquet/write/levels.rs
  src/io/parquet/write/mod.rs
  src/io/parquet/write/primitive/basic.rs
  src/io/parquet/write/primitive/nested.rs
  src/io/parquet/write/row_group.rs
  src/io/parquet/write/sink.rs
  src/io/parquet/write/utf8/basic.rs
  src/io/parquet/write/utf8/nested.rs
  src/io/parquet/write/utils.rs
  tests/it/io/parquet/mod.rs
  tests/it/io/parquet/read.rs
  tests/it/io/parquet/read_indexes.rs
Labels: bug

#985 Allowed feature-specific test runs
  tests/it/io/mod.rs
  tests/it/io/parquet/integration.rs
  tests/it/io/parquet/mod.rs
  tests/it/io/parquet/read.rs
  tests/it/io/parquet/write.rs
Labels: testing

#989 Support for deserializing JSON from Utf8Array
  src/io/json/read/deserialize.rs
  src/io/ndjson/read/deserialize.rs
  src/io/ndjson/read/file.rs
  src/io/ndjson/read/mod.rs
  tests/it/io/ndjson/mod.rs
  tests/it/io/ndjson/read.rs
Labels: feature

#1002 Replace `fn Offset::is_large()` as `const Offset::IS_LARGE`
  src/array/binary/fmt.rs
  src/array/binary/mod.rs
  src/array/list/fmt.rs
  src/array/list/mod.rs
  src/array/list/mutable.rs
  src/array/utf8/fmt.rs
  src/array/utf8/mod.rs
  src/array/utf8/mutable.rs
  src/compute/length.rs
  src/scalar/binary.rs
  src/scalar/utf8.rs
  src/types/offset.rs
  tests/it/compute/length.rs
Labels: backwards-incompatible

#1003 Fixed dev guide
  DEVELOPMENT.md
Labels: documentation

#1001 Moved tests from lib to `tests`
  src/bitmap/mod.rs
  src/bitmap/utils/fmt.rs
  src/types/bit_chunk.rs
  tests/it/bitmap/mod.rs
  tests/it/bitmap/utils/fmt.rs
  tests/it/bitmap/utils/mod.rs
  tests/it/main.rs
  tests/it/types.rs
Labels: testing

#998 Added support for Decimal in `build_compare`
  src/array/ord.rs
  tests/it/array/ord.rs
Labels: enhancement

#1004 Rewrite `min_max_string` and `min_max_binary`
  benches/aggregate.rs
  src/compute/aggregate/min_max.rs
  tests/it/compute/aggregate/min_max.rs
Labels: enhancement

#1009 Treat empty timezone string as no-timezone
  src/array/primitive/fmt.rs
  src/ffi/schema.rs
Labels: bug

#1011 Bumped arrow-format
  Cargo.toml
  integration-testing/Cargo.toml
Labels: backwards-incompatible

#1007 Added support to write nested parquet
  arrow-parquet-integration-testing/src/main.rs
  benches/write_parquet.rs
  examples/parquet_write.rs
  src/doc/lib.md
  src/io/parquet/write/binary/nested.rs
  src/io/parquet/write/boolean/nested.rs
  src/io/parquet/write/levels.rs
  src/io/parquet/write/mod.rs
  src/io/parquet/write/nested/def.rs
  src/io/parquet/write/nested/mod.rs
  src/io/parquet/write/nested/rep.rs
  src/io/parquet/write/pages.rs
  src/io/parquet/write/primitive/nested.rs
  src/io/parquet/write/row_group.rs
  src/io/parquet/write/sink.rs
  src/io/parquet/write/utf8/nested.rs
  tests/it/io/parquet/mod.rs
  tests/it/io/parquet/read_indexes.rs
  tests/it/io/parquet/write.rs
  tests/it/io/parquet/write_async.rs
Labels: feature

#1013 Fixed panic on debug print of invalid timezones
  src/array/primitive/fmt.rs
  tests/it/array/primitive/fmt.rs
Labels: bug

#1015 Fix error in reading nested parquet structs
  src/io/parquet/read/deserialize/binary/mod.rs
  src/io/parquet/read/deserialize/binary/nested.rs
  src/io/parquet/read/deserialize/boolean/mod.rs
  src/io/parquet/read/deserialize/boolean/nested.rs
  src/io/parquet/read/deserialize/mod.rs
  src/io/parquet/read/deserialize/nested_utils.rs
  src/io/parquet/read/deserialize/primitive/mod.rs
  src/io/parquet/read/deserialize/primitive/nested.rs
  src/io/parquet/read/deserialize/struct_.rs
Labels: bug

#1016 Added support for custom sort `build_compare_fn`
  src/compute/merge_sort/mod.rs
  src/compute/sort/lex_sort.rs
  src/compute/sort/mod.rs
Labels: feature

#1018 Added utility to create encodings
  examples/parquet_write.rs
  src/io/parquet/read/deserialize/mod.rs
  src/io/parquet/write/mod.rs
Labels: enhancement

#1019 Fixed error in writing `list<struct<..>>` to parquet
  src/io/parquet/write/nested/rep.rs
Labels: bug, no-changelog

#1017 Improved API docs for `PrimitiveArray` and `Utf8Array`
  src/array/binary/mod.rs
  src/array/equal/utf8.rs
  src/array/fixed_size_binary/mod.rs
  src/array/primitive/from_natural.rs
  src/array/primitive/iterator.rs
  src/array/primitive/mod.rs
  src/array/utf8/from.rs
  src/array/utf8/iterator.rs
  src/array/utf8/mod.rs
  src/io/ipc/write/file_async.rs
  src/io/ipc/write/stream_async.rs
  src/types/bit_chunk.rs
Labels: documentation

#1022 Improved docs for `bitmap`
  src/bitmap/immutable.rs
  src/bitmap/mutable.rs
  src/bitmap/utils/mod.rs
  src/io/ipc/read/read_basic.rs
  src/types/bit_chunk.rs
Labels: documentation

#1020 Remove `from_trusted_len_*` from `Buffer`
  guide/src/high_level.md
  src/array/binary/mod.rs
  src/array/fixed_size_binary/mod.rs
  src/array/list/mod.rs
  src/array/map/mod.rs
  src/array/mod.rs
  src/array/primitive/mod.rs
  src/array/union/mod.rs
  src/array/utf8/mod.rs
  src/buffer/immutable.rs
  tests/it/array/binary/mod.rs
  tests/it/array/equal/list.rs
  tests/it/array/fixed_size_binary/mod.rs
  tests/it/array/list/mod.rs
  tests/it/array/list/mutable.rs
  tests/it/array/primitive/mod.rs
  tests/it/array/union.rs
  tests/it/array/utf8/mod.rs
  tests/it/buffer/immutable.rs
  tests/it/compute/take.rs
  tests/it/io/json/write.rs
  tests/it/io/ndjson/mod.rs
  tests/it/io/parquet/mod.rs
  tests/it/io/print.rs
Labels: help wanted, backwards-incompatible

#1025 Improved API docs for `MutableBitmap`
  src/bitmap/mutable.rs
Labels: documentation

#1026 Fixed error in consuming sliced `FixedSizedBinary` from c data interface (FFI)
  src/ffi/array.rs
  tests/it/ffi/data.rs
Labels: bug

#1029 Added more tests
  src/array/fixed_size_binary/iterator.rs
  tests/it/array/primitive/mutable.rs
  tests/it/ffi/data.rs
Labels: testing

#1032 Fixed error in reading tz with a ":" offset
  src/ffi/schema.rs
Labels: bug, no-changelog

#1034 Added support for random access reads to IPC
  examples/ipc_file_read.rs
  src/io/ipc/append/mod.rs
  src/io/ipc/read/mod.rs
  src/io/ipc/read/reader.rs
Labels: feature
