Repository jorgecarleitao/arrow2, pull requests merged in 2022-09, with the labels that each got.

#1238 Added documentation on parquet compatibility under `TimeUnit`.
  src/io/parquet/write/mod.rs
Labels: documentation

#1240 Fixed reading nested stats
  examples/parquet_read.rs
  src/io/parquet/read/statistics/list.rs
Labels: bug

#1241 Simpler nested parquet read
  src/io/parquet/read/deserialize/nested_utils.rs
Labels: enhancement

#1194 Added support for decimal 256
  Cargo.toml
  arrow-pyarrow-integration-testing/tests/test_sql.py
  src/array/mod.rs
  src/array/primitive/fmt.rs
  src/array/primitive/mod.rs
  src/compute/arithmetics/mod.rs
  src/compute/comparison/mod.rs
  src/compute/comparison/simd/native.rs
  src/compute/comparison/simd/packed.rs
  src/datatypes/mod.rs
  src/ffi/schema.rs
  src/io/ipc/read/schema.rs
  src/io/ipc/write/schema.rs
  src/io/json_integration/read/array.rs
  src/io/json_integration/read/schema.rs
  src/io/json_integration/write/schema.rs
  src/types/mod.rs
  src/types/native.rs
  src/types/simd/mod.rs
  tests/it/io/ipc/write/file.rs
Labels: investigation

#1246 Added schema to FileReader
  src/io/parquet/read/file.rs
Labels: enhancement

#1247 Fixed guide and improved examples
  .github/workflows/docs.yml
  README.md
  examples/ipc_file_mmap.rs
  guide/src/README.md
  guide/src/high_level.md
  guide/src/io/README.md
  guide/src/io/odbc.md
  guide/src/io/parquet_read.md
  src/io/ipc/write/common.rs
  src/io/ipc/write/writer.rs
Labels: documentation

#1250 Improved test for nullable struct read from Avro
  tests/it/io/avro/read.rs
Labels: testing

#1253 Fixed error reading unbounded Avro list
  src/io/avro/read/deserialize.rs
  tests/it/io/avro/read.rs
Labels: bug

#1258 Removed un-used code
  src/io/parquet/write/nested/mod.rs
Labels: bug

#1259 Fixed clippy for 1.60
  src/lib.rs
  tests/it/main.rs
Labels: enhancement

#1255 Added `BinaryArray::into_mut` and double-ended support for its iterator
  src/array/binary/iterator.rs
  src/array/binary/mod.rs
  src/array/binary/mutable.rs
  src/io/parquet/write/binary/basic.rs
  tests/it/array/binary/mod.rs
  tests/it/array/binary/to_mutable.rs
Labels: enhancement
