Repository jorgecarleitao/arrow2, pull requests merged in 2023-03, with the labels that each got.

#1424 Added support for JSON serialization of dictionary
  src/io/json/write/serialize.rs
  tests/it/io/json/write.rs
Labels: feature

#1428 Added MapScalar
  src/scalar/equal.rs
  src/scalar/map.rs
  src/scalar/mod.rs
  tests/it/scalar/map.rs
  tests/it/scalar/mod.rs
Labels: feature

#1427 Changed encoded float::Inf as null in json
  DEVELOPMENT.md
  src/io/json/write/serialize.rs
  tests/it/io/json/write.rs
Labels: bug

#1434 Made `len/len_proxy` consistent with `Offsets`
  src/array/binary/mod.rs
  src/array/list/mod.rs
  src/array/map/mod.rs
  src/array/utf8/mod.rs
  src/compute/aggregate/memory.rs
  src/io/parquet/write/pages.rs
  src/offset.rs
Labels: backwards-incompatible

#1435 Added impl_mutable_array_mut_validity macro for mutable arrays
  src/array/binary/mutable.rs
  src/array/mod.rs
  tests/it/array/binary/mutable.rs
Labels: enhancement

#1437 Added buffer interoperability with arrow-rs (#1429)
  Cargo.toml
  src/bitmap/immutable.rs
  src/buffer/immutable.rs
  src/buffer/mod.rs
  src/ffi/array.rs
  src/types/native.rs
  tests/it/bitmap/immutable.rs
  tests/it/buffer/immutable.rs
Labels: feature

#1439 Changed async ipc writer to accept schema by value
  src/io/ipc/write/file_async.rs
  tests/it/io/ipc/write_file_async.rs
Labels: backwards-incompatible

#1440 Updated multiversion and support wider registers
  Cargo.toml
  src/compute/aggregate/min_max.rs
  src/compute/aggregate/sum.rs
  src/compute/hash.rs
Labels: enhancement

#1441 Updated dependencies
  Cargo.toml
Labels: enhancement

#1442 Added interoperability with arrow-schema
  Cargo.toml
  src/datatypes/field.rs
  src/datatypes/mod.rs
Labels: enhancement
