Repository jorgecarleitao/arrow2, pull requests merged in 2023-02, with the labels that each got.

#1375 Made some structs and functions public
  src/io/parquet/read/deserialize/mod.rs
  src/io/parquet/read/deserialize/nested_utils.rs
  src/io/parquet/read/mod.rs
  src/io/parquet/write/mod.rs
  src/io/parquet/write/nested/mod.rs
  src/io/parquet/write/pages.rs
Labels: enhancement

#1373 Fixed typo in `OffsetsBuffer` docs
  src/offset.rs
Labels: documentation

#1380 Renamed `factory` argument on parquet read functions to `reader_factory`
  src/io/parquet/read/row_group.rs
Labels: enhancement

#1386 Added support for `take` of `FixedSizeListArray`
  src/compute/take/fixed_size_list.rs
  src/compute/take/mod.rs
  tests/it/compute/take.rs
Labels: enhancement

#1390 Fixed writing nested parquet
  parquet_integration/write_parquet.py
  src/io/parquet/write/binary/nested.rs
  src/io/parquet/write/boolean/nested.rs
  src/io/parquet/write/dictionary.rs
  src/io/parquet/write/nested/def.rs
  src/io/parquet/write/nested/mod.rs
  src/io/parquet/write/nested/rep.rs
  src/io/parquet/write/primitive/nested.rs
  src/io/parquet/write/utf8/nested.rs
  tests/it/io/parquet/mod.rs
  tests/it/io/parquet/read.rs
  tests/it/io/parquet/write.rs
Labels: bug

#1391 Fixed error in writing sliced binary
  src/io/parquet/write/binary/nested.rs
Labels: bug

#1395 Fixed broken guide link
  guide/src/SUMMARY.md
  guide/src/io/csv_read.md
Labels: documentation

#1397 Fixed writing of sliced arrays to parquet
  src/buffer/immutable.rs
  src/io/parquet/write/binary/nested.rs
  src/io/parquet/write/mod.rs
  src/io/parquet/write/nested/def.rs
  src/io/parquet/write/nested/rep.rs
  src/io/parquet/write/pages.rs
  src/io/parquet/write/primitive/nested.rs
  src/io/parquet/write/utf8/nested.rs
  src/offset.rs
  tests/it/io/parquet/mod.rs
Labels: bug

#1398 Simplified code via DRY
  src/array/binary/mod.rs
  src/array/boolean/mod.rs
  src/array/dictionary/mod.rs
  src/array/fixed_size_binary/mod.rs
  src/array/fixed_size_list/mod.rs
  src/array/list/mod.rs
  src/array/map/mod.rs
  src/array/mod.rs
  src/array/null.rs
  src/array/primitive/mod.rs
  src/array/struct_/mod.rs
  src/array/union/mod.rs
  src/array/utf8/mod.rs
Labels: enhancement

#1399 Improved API of getting mutable from Buffer
  src/array/binary/mod.rs
  src/array/primitive/mod.rs
  src/array/utf8/mod.rs
  src/buffer/immutable.rs
  src/offset.rs
Labels: enhancement

#1401 Simplified code
  src/io/parquet/read/deserialize/binary/basic.rs
  src/io/parquet/read/deserialize/binary/nested.rs
  src/io/parquet/read/deserialize/nested.rs
  src/io/parquet/read/deserialize/simple.rs
Labels: enhancement

#1402 Improved support for date64 written by pyarrow to parquet
  src/io/parquet/read/deserialize/simple.rs
  src/io/parquet/read/statistics/mod.rs
Labels: enhancement

#1406 Added apply_validity and set_validity to mutable utf8 array
  src/array/utf8/mutable.rs
  tests/it/array/utf8/mutable.rs
Labels: enhancement

#1407 Fixed ahash dependency for wasm
  Cargo.toml
Labels: bug

#1403 Added cast for FixedSizeBinary to (Large)Binary
  src/compute/cast/binary_to.rs
  src/compute/cast/mod.rs
  tests/it/compute/cast.rs
Labels: enhancement

#1414 Fixed statistics writing flag and correct null_count in dictionaries
  src/io/parquet/write/dictionary.rs
  tests/it/io/parquet/mod.rs
Labels: bug

#1419 Added support for MapArray read and write to parquet
  src/array/fmt.rs
  src/array/growable/map.rs
  src/array/growable/mod.rs
  src/array/map/mod.rs
  src/io/parquet/read/deserialize/mod.rs
  src/io/parquet/read/deserialize/nested.rs
  src/io/parquet/read/indexes/mod.rs
  src/io/parquet/read/mod.rs
  src/io/parquet/write/mod.rs
  src/io/parquet/write/pages.rs
  src/io/parquet/write/schema.rs
  tests/it/array/growable/map.rs
  tests/it/array/growable/mod.rs
  tests/it/io/parquet/mod.rs
  tests/it/io/parquet/write.rs
Labels: feature
